Repository orchest/orchest, pull requests merged in 2022-09, with the labels that each got.

#1244 Dynamically update the pipeline of a job draft
  services/orchest-api/app/app/apis/namespace_jobs.py
  services/orchest-api/app/app/schema.py
  services/orchest-webserver/app/app/core/jobs.py
  services/orchest-webserver/app/app/error.py
  services/orchest-webserver/app/app/views/orchest_api.py
Labels: new feature request

#1224 Remove periodic builder cache cleanup task
  docs/source/development/appendix.md
  orchest-cli/orchestcli/_version.py
  orchest-cli/orchestcli/cli.py
  orchest-cli/orchestcli/cmds.py
  orchest-cli/orchestcli/utils.py
  services/orchest-api/app/app/apis/namespace_ctl.py
  services/orchest-api/app/app/core/image_utils.py
  services/orchest-api/app/app/core/scheduler.py
  services/orchest-api/app/app/core/tasks.py
  services/orchest-api/app/config.py
  services/orchest-controller/pkg/apis/orchest/v1alpha1/types.go
  services/orchest-controller/pkg/controller/controller_utils.go
  services/orchest-controller/pkg/controller/orchestcluster/cluster_controller.go
  services/orchest-webserver/app/app/views/orchest_api.py
Labels: internal

#1240 Introduce `Snapshot` entity in models
  services/orchest-api/app/app/apis/__init__.py
  services/orchest-api/app/app/apis/namespace_jobs.py
  services/orchest-api/app/app/apis/namespace_snapshots.py
  services/orchest-api/app/app/models/__init__.py
  services/orchest-api/app/app/models/_core.py
  services/orchest-api/app/app/schema.py
  services/orchest-api/app/app/utils.py
  services/orchest-api/app/migrations/versions/7beba3ba9e66_.py
  services/orchest-api/app/migrations/versions/8e05af5f2b06_.py
  services/orchest-api/app/migrations/versions/ba252b957597_.py
  services/orchest-api/app/migrations/versions/c5b150e99eda_.py
  services/orchest-api/app/migrations/versions/f2b64bf97de0_.py
  services/orchest-webserver/app/app/core/jobs.py
  services/orchest-webserver/app/app/error.py
  services/orchest-webserver/app/app/utils.py
  services/orchest-webserver/app/app/views/orchest_api.py
  services/orchest-webserver/client/src/types.d.ts
Labels: internal

#1216 Add type hints to auth server app
  README.md
  services/auth-server/app/app/utils.py
  services/auth-server/app/app/views.py
Labels: internal

#1214 Improve pipeline run performance on single-node Orchest deployments
  docs/source/getting_started/installation.md
  lib/python/orchest-internals/_orchest/internals/config.py
  services/orchest-api/app/app/core/pipelines.py
  services/orchest-api/app/app/core/sessions/_manifests.py
  services/orchest-api/app/app/types.py
  services/orchest-api/app/app/utils.py
  services/orchest-api/app/config.py
  services/orchest-controller/deploy/thirdparty/argo-workflows/orchest-values.yaml
  services/orchest-controller/pkg/controller/orchestcluster/cluster_controller.go
Labels: improvement

#1250 Tweak Orchest to better handle times of CPU contention
  docs/source/development/development_workflow.md
  docs/source/getting_started/installation.md
  docs/source/reference/cli/index.md
  lib/python/orchest-internals/_orchest/internals/config.py
  services/orchest-api/app/app/core/pipelines.py
  services/orchest-api/app/app/core/sessions/_manifests.py
  services/orchest-controller/cmd/controller/cmd/controller.go
  services/orchest-controller/pkg/controller/controller.go
  services/orchest-controller/pkg/controller/minikubereconciler/minikube_controller.go
  services/orchest-controller/pkg/controller/orchestcluster/cluster_controller.go
  services/orchest-controller/pkg/controller/orchestcluster/cluster_utils.go
  services/orchest-controller/pkg/controller/orchestcomponent/auth_server.go
  services/orchest-controller/pkg/controller/orchestcomponent/celery_worker.go
  services/orchest-controller/pkg/controller/orchestcomponent/component_controller.go
  services/orchest-controller/pkg/controller/orchestcomponent/orchest_api.go
  services/orchest-controller/pkg/controller/orchestcomponent/orchest_database.go
  services/orchest-controller/pkg/controller/orchestcomponent/orchest_webserver.go
  services/orchest-controller/pkg/controller/watcher.go
  services/orchest-controller/pkg/utils/k8s_utils.go
Labels: improvement

#1256 Write to JupyterLab user settings during custom Jupyter server build
  services/jupyter-server/Dockerfile
  services/orchest-api/app/app/core/image_utils.py
  services/orchest-api/app/app/core/jupyter_image_builds.py
  utility-containers/image-builder-buildkit/Dockerfile
  utility-containers/image-builder-buildx/Dockerfile
Labels: internal

#1248 Environment shells
  docs/source/fundamentals/environments.md
  docs/source/img/environment-shells-jupyterlab.png
  lib/python/orchest-internals/_orchest/internals/config.py
  lib/python/orchest-internals/_orchest/internals/utils.py
  orchest-cli/orchestcli/cmds.py
  orchest-sdk/python/orchest/_version.py
  orchest-sdk/python/orchest/utils.py
  scripts/build_container.sh
  services/base-images/base-kernel-javascript/Dockerfile
  services/base-images/base-kernel-julia/Dockerfile
  services/base-images/base-kernel-py/Dockerfile
  services/base-images/base-kernel-r/Dockerfile
  services/base-images/runnable-shared/bootscript.sh
  services/jupyter-server/Dockerfile
  services/jupyter-server/requirements.in
  services/jupyter-server/requirements.txt
  services/jupyter-server/shellspawner/shellspawner
  services/orchest-api/app/app/apis/__init__.py
  services/orchest-api/app/app/apis/namespace_environment_shells.py
  services/orchest-api/app/app/core/environment_shells.py
  services/orchest-api/app/app/core/sessions/_manifests.py
  services/orchest-api/app/app/schema.py
  services/orchest-webserver/app/app/views/orchest_api.py
Labels: new feature request

#1227 Allow parallelism for environment and jupyter builds
  docs/source/fundamentals/settings.md
  lib/python/orchest-internals/_orchest/internals/analytics.py
  services/node-agent/app/image_pusher.py
  services/orchest-api/app/app/apis/namespace_ctl.py
  services/orchest-api/app/app/apis/namespace_environment_images.py
  services/orchest-api/app/app/core/scheduler.py
  services/orchest-api/app/app/core/tasks.py
  services/orchest-api/app/app/models/_core.py
  services/orchest-api/app/app/utils.py
  services/orchest-api/app/config.py
  services/orchest-api/app/migrations/versions/166e07b0e9f1_.py
  services/orchest-api/app/migrations/versions/1cc5332f9b55_.py
  services/orchest-api/app/migrations/versions/66b801f7abfc_.py
  services/orchest-api/celery_daemon_configs/worker_builds.conf
  services/orchest-api/start_celery_daemon.sh
  services/orchest-webserver/client/src/__mocks__/mockConfig.mock.tsx
  services/orchest-webserver/client/src/types.d.ts
Labels: new feature request

#1221 Change image digest management
  docs/source/development/appendix.md
  docs/source/fundamentals/settings.md
  lib/python/orchest-internals/_orchest/internals/analytics.py
  orchest-cli/orchestcli/_version.py
  orchest-cli/orchestcli/cli.py
  orchest-cli/orchestcli/cmds.py
  orchest-cli/orchestcli/utils.py
  services/node-agent/app/image_pusher.py
  services/orchest-api/app/app/apis/namespace_ctl.py
  services/orchest-api/app/app/apis/namespace_environment_image_builds.py
  services/orchest-api/app/app/apis/namespace_environment_images.py
  services/orchest-api/app/app/apis/namespace_jupyter_image_builds.py
  services/orchest-api/app/app/core/environment_image_builds.py
  services/orchest-api/app/app/core/environments.py
  services/orchest-api/app/app/core/image_utils.py
  services/orchest-api/app/app/core/jupyter_image_builds.py
  services/orchest-api/app/app/core/scheduler.py
  services/orchest-api/app/app/core/tasks.py
  services/orchest-api/app/app/models/_core.py
  services/orchest-api/app/app/utils.py
  services/orchest-api/app/config.py
  services/orchest-api/app/migrations/versions/166e07b0e9f1_.py
  services/orchest-api/app/migrations/versions/1cc5332f9b55_.py
  services/orchest-api/app/migrations/versions/66b801f7abfc_.py
  services/orchest-api/app/migrations/versions/6ca72589ff64_.py
  services/orchest-api/app/migrations/versions/7497b5211902_.py
  services/orchest-api/celery_daemon_configs/worker_builds.conf
  services/orchest-api/start_celery_daemon.sh
  services/orchest-controller/pkg/apis/orchest/v1alpha1/types.go
  services/orchest-controller/pkg/controller/controller_utils.go
  services/orchest-controller/pkg/controller/orchestcluster/cluster_controller.go
  services/orchest-webserver/app/app/views/orchest_api.py
  services/orchest-webserver/client/src/__mocks__/mockConfig.mock.tsx
  services/orchest-webserver/client/src/types.d.ts
  utility-containers/image-puller/pull_image.sh
Labels: internal

#1253 Build images on the node directly
  .github/workflows/docker-ci.yml
  docs/source/development/development_workflow.md
  lib/python/orchest-internals/_orchest/internals/config.py
  scripts/build_container.sh
  services/buildkit-daemon/Dockerfile
  services/buildkit-daemon/buildkitd.toml
  services/jupyter-server/Dockerfile
  services/node-agent/app/image_deleter.py
  services/orchest-api/app/app/__init__.py
  services/orchest-api/app/app/apis/namespace_ctl.py
  services/orchest-api/app/app/core/environment_image_builds.py
  services/orchest-api/app/app/core/image_utils.py
  services/orchest-api/app/app/core/jupyter_image_builds.py
  services/orchest-api/app/config.py
  services/orchest-controller/pkg/apis/orchest/v1alpha1/types.go
  services/orchest-controller/pkg/apis/orchest/v1alpha1/zz_generated.deepcopy.go
  services/orchest-controller/pkg/controller/controller_utils.go
  services/orchest-controller/pkg/controller/orchestcluster/cluster_controller.go
  services/orchest-controller/pkg/controller/orchestcluster/cluster_utils.go
  services/orchest-controller/pkg/controller/orchestcomponent/buildkit_daemon.go
  services/orchest-controller/pkg/controller/orchestcomponent/component_controller.go
  services/orchest-controller/pkg/controller/orchestcomponent/node_agent.go
  utility-containers/image-builder-buildkit/Dockerfile
  utility-containers/image-builder-buildx/Dockerfile
  utility-containers/image-puller/Dockerfile
Labels: improvement

#1259 Print help message if orchest-cli did not install in PATH
  scripts/convenience_install.sh
Labels: improvement

#1262 Shift responsibility of kernels pod creation to `orchest-api`
  lib/python/orchest-internals/_orchest/internals/config.py
  services/node-agent/app/image_puller.py
  services/node-agent/app/image_pusher.py
  services/orchest-api/app/app/apis/namespace_ctl.py
  services/orchest-api/app/app/apis/namespace_environment_images.py
  services/orchest-api/app/app/apis/namespace_sessions.py
  services/orchest-api/app/app/core/environments.py
  services/orchest-api/app/app/core/sessions/_manifests.py
  services/orchest-api/app/app/schema.py
  services/orchest-api/app/app/utils.py
  services/orchest-webserver/app/app/res/kernels/launch_kubernetes.py
Labels: internal

#1263 Alter pods scheduling based on image location across the cluster
  lib/python/orchest-internals/_orchest/internals/utils.py
  services/node-agent/app/image_pusher.py
  services/orchest-api/app/app/apis/namespace_sessions.py
  services/orchest-api/app/app/core/pipelines.py
  services/orchest-api/app/app/core/pod_scheduling.py
  services/orchest-api/app/app/core/scheduler.py
  services/orchest-api/app/app/core/sessions/_manifests.py
  services/orchest-api/app/app/core/tasks.py
Labels: improvement

#1273 Update file tree when pipeline is deleted
  services/orchest-webserver/client/src/pipeline-view/pipeline-canvas-header-bar/PipelineMoreOptionsMenu.tsx
Labels: fix

#1272 More empty state actions
  services/orchest-webserver/client/src/components/common/EmptyState.tsx
  services/orchest-webserver/client/src/environments-view/CreateEnvironmentButton.tsx
  services/orchest-webserver/client/src/environments-view/EnvironmentMenuList.tsx
  services/orchest-webserver/client/src/environments-view/EnvironmentMoreOptions.tsx
  services/orchest-webserver/client/src/environments-view/edit-environment/EditEnvironmentContainer.tsx
  services/orchest-webserver/client/src/environments-view/edit-environment/NoEnvironment.tsx
  services/orchest-webserver/client/src/environments-view/hooks/useCreateEnvironment.tsx
  services/orchest-webserver/client/src/environments-view/hooks/useSelectEnvironment.tsx
  services/orchest-webserver/client/src/jobs-view/CreateJobButton.tsx
  services/orchest-webserver/client/src/jobs-view/hooks/useCreateJob.tsx
  services/orchest-webserver/client/src/jobs-view/job-view/NoJob.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-canvas-header-bar/primary-action/usePipelineActions.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/NoPipeline.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/NoStep.tsx
  services/orchest-webserver/client/src/pipeline-view/step-details/StepCreateEnvironmentButton.tsx
  services/orchest-webserver/client/src/projects-view/NoProject.tsx
Labels: improvement

#1275 fix: App crashed when creating an environment from PipelineEditor
  services/orchest-webserver/client/src/environments-view/hooks/useCreateEnvironment.tsx
Labels: fix

#1281 Only create session sidecar if needed
  services/orchest-api/app/app/core/sessions/_core.py
Labels: bug

#1282 Fix settings DB records stating that a restart is required on install
  services/orchest-api/app/app/utils.py
Labels: bug

#1284 Fix k3s support
  docs/source/_static/js/installer_widget.js
  services/orchest-controller/pkg/controller/orchestcomponent/buildkit_daemon.go
Labels: fix

#1279 Fix: You get navigated back into JupyterLab on load
  services/orchest-webserver/client/src/jupyter/Jupyter.tsx
  services/orchest-webserver/client/src/views/JupyterLabView.tsx
Labels: fix

#1286 Don't autostart sessions for job runs
  services/orchest-webserver/client/src/pipeline-view/contexts/PipelineDataContext.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useAutoStartSession.tsx
Labels: fix

#1293 fix: Unable to create a file in /data folder
  services/orchest-webserver/client/src/pipeline-view/file-manager/ActionBar.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/common.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useCreateStep.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineViewport.tsx
Labels: fix

#1298 Update images in docs to use new UI
  docs/source/fundamentals/data_passing.rst
  docs/source/fundamentals/environments.md
  docs/source/fundamentals/jobs.md
  docs/source/fundamentals/pipelines.md
  docs/source/fundamentals/projects.md
  docs/source/fundamentals/services.md
  docs/source/getting_started/faq.md
  docs/source/getting_started/quickstart.md
  docs/source/img/environment-config.png
  docs/source/img/environments-list.png
  docs/source/img/job-new.png
  docs/source/img/jobs-list.png
  docs/source/img/logs-pointer.png
  docs/source/img/pipeline-editor.png
  docs/source/img/pipeline.png
  docs/source/img/project-import.png
  docs/source/img/quickstart/file-creation.png
  docs/source/img/quickstart/final-pipeline-completed.png
  docs/source/img/quickstart/final-pipeline.png
  docs/source/img/quickstart/import-project.png
  docs/source/img/quickstart/pipeline-two-steps.png
  docs/source/img/quickstart/project-creation.png
  docs/source/img/quickstart/step-logs.png
  docs/source/img/quickstart/step-properties.png
  docs/source/img/quickstart/upload-file.png
  docs/source/img/service-logs.png
  docs/source/img/services-pointer.png
  docs/source/img/step-connections.png
Labels: improvement

#1297 Increase live/readiness probes timeouts
  services/orchest-controller/deploy/thirdparty/ingress-nginx/orchest-values.yaml
  services/orchest-controller/pkg/controller/orchestcomponent/orchest_api.go
  services/orchest-controller/pkg/controller/orchestcomponent/orchest_database.go
Labels: internal

#1296 fix: PipelineLogs should show all steps.
  services/orchest-webserver/client/src/pipeline-view/pipeline-logs-dialog/PipelineLogs.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-logs-dialog/common.tsx
Labels: fix

#1294 Clear step logs on interactive run request
  lib/python/orchest-internals/_orchest/internals/utils.py
  services/orchest-webserver/app/app/utils.py
  services/orchest-webserver/app/app/views/orchest_api.py
  services/orchest-webserver/app/scripts/log_streamer.py
Labels: improvement

#1300 Expanded canvas: the simple solution.
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineCanvas.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineCanvasBackground.tsx
  services/orchest-webserver/client/src/styles/main.scss
  services/orchest-webserver/client/src/utils/math.ts
Labels: improvement

#1295 Display the "no steps" empty state when no steps have been created but there are scripts available
  services/orchest-webserver/client/public/image/no-steps.svg
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/NoScripts.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/NoSteps.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineViewport.tsx
Labels: fix

#1304 Show dialog when session is stopping and you open JupyterLab
  services/orchest-webserver/client/src/jupyter/Jupyter.tsx
  services/orchest-webserver/client/src/views/JupyterLabView.tsx
Labels: improvement

#1308 Disable "run incoming" if there are no incoming
  services/orchest-webserver/client/src/pipeline-view/pipeline-canvas-header-bar/primary-action/PrimaryPipelineActionMenu.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineViewportContextMenu.tsx
Labels: fix

#1315 fix: Jobs view crashes on Safari
  services/orchest-webserver/client/src/jobs-view/common.tsx
  services/orchest-webserver/client/src/utils/date-time.ts
Labels: fix

#1321 ORC-908: Background color for chips in run table
  services/orchest-webserver/client/src/jobs-view/job-view/JobRunsTable.tsx
Labels: improvement
