Repository orchest/orchest, pull requests merged in 2022-06, with the labels that each got.

#1012 Fix key press not working in Jupyter Lab issue
  services/orchest-webserver/client/src/jupyter/Jupyter.tsx
Labels: fix

#980 Improve consistency of `orchest-webserver` telemetry events
  lib/python/orchest-internals/_orchest/internals/analytics.py
  services/orchest-webserver/app/app/views/orchest_api.py
  services/orchest-webserver/app/app/views/views.py
Labels: internal

#963 Add environment image builds events to `orchest-api` (notifications)
  lib/python/orchest-internals/_orchest/internals/analytics.py
  services/orchest-api/app/app/apis/namespace_environment_image_builds.py
  services/orchest-api/app/app/core/events.py
  services/orchest-api/app/app/core/notifications/analytics.py
  services/orchest-api/app/app/models.py
  services/orchest-api/app/app/utils.py
  services/orchest-api/app/migrations/versions/0eaf40410361_.py
  services/orchest-webserver/app/app/views/orchest_api.py
Labels: improvement, internal

#975 Add developer docs for telemetry and `orchest-api` events
  docs/source/development/feature_manuals.rst
  docs/source/index.rst
  lib/python/orchest-internals/_orchest/internals/analytics.py
  services/orchest-webserver/app/app/views/orchest_api.py
  services/orchest-webserver/app/app/views/views.py
Labels: internal

#1002 Add troubleshooting outdated controller section
  docs/source/development/troubleshooting.rst
Labels: internal

#974 Shift anonymization responsibility to analytics module callers, part 2
  docs/source/development/feature_manuals.rst
  docs/source/index.rst
  lib/python/orchest-internals/_orchest/internals/analytics.py
  services/orchest-api/app/app/models/_events.py
  services/orchest-webserver/app/app/views/orchest_api.py
  services/orchest-webserver/app/app/views/views.py
Labels: internal

#970 Shift anonymization responsibility to analytics module callers, part 1
  .flake8
  docs/source/development/feature_manuals.rst
  docs/source/index.rst
  lib/python/orchest-internals/_orchest/internals/analytics.py
  services/orchest-api/app/app/core/events.py
  services/orchest-api/app/app/core/notifications/analytics.py
  services/orchest-api/app/app/models/__init__.py
  services/orchest-api/app/app/models/_core.py
  services/orchest-api/app/app/models/_events.py
  services/orchest-webserver/app/app/core/scheduler.py
  services/orchest-webserver/app/app/views/analytics.py
  services/orchest-webserver/app/app/views/orchest_api.py
  services/orchest-webserver/app/app/views/views.py
Labels: internal

#1023 Fix pipeline auto-saving when deleting steps
  services/orchest-webserver/client/src/pipeline-view/PipelineEditor.tsx
Labels: fix

#1025 Fix UI flickering when polling
  services/orchest-webserver/client/src/components/DataTable.tsx
  services/orchest-webserver/client/src/hooks/useAsync.ts
  services/orchest-webserver/client/src/hooks/useFetchPipelineJson.ts
  services/orchest-webserver/client/src/hooks/useFetcher.ts
  services/orchest-webserver/client/src/hooks/useSessionsPoller.ts
  services/orchest-webserver/client/src/pipeline-view/hooks/useStepExecutionState.tsx
Labels: fix

#1008 Sending notifications when jobs fail.
  docs/requirements.txt
  docs/source/conf.py
  docs/source/fundamentals/notifications.md
  docs/source/index.rst
  lib/javascript/utils/src/fetcher.ts
  lib/javascript/utils/src/typed.ts
  services/orchest-api/app/app/apis/namespace_notifications.py
  services/orchest-api/app/app/core/notifications/webhooks.py
  services/orchest-api/app/app/models.py
  services/orchest-api/app/app/schema.py
  services/orchest-api/app/app/utils.py
  services/orchest-api/app/migrations/versions/aa7e3a012836_.py
  services/orchest-webserver/app/app/views/orchest_api.py
  services/orchest-webserver/client/src/Routes.tsx
  services/orchest-webserver/client/src/components/DataTable.tsx
  services/orchest-webserver/client/src/components/SessionToggleButton.tsx
  services/orchest-webserver/client/src/components/common/SectionTitle.tsx
  services/orchest-webserver/client/src/contexts/AppInnerContext.tsx
  services/orchest-webserver/client/src/hooks/useAsync.ts
  services/orchest-webserver/client/src/hooks/useCustomRoute.ts
  services/orchest-webserver/client/src/hooks/useFetcher.ts
  services/orchest-webserver/client/src/hooks/useLocalStorage.ts
  services/orchest-webserver/client/src/jobs-view/JobList.tsx
  services/orchest-webserver/client/src/notification-settings-view/NotificationEventsForm.tsx
  services/orchest-webserver/client/src/notification-settings-view/NotificationSettingsContext.tsx
  services/orchest-webserver/client/src/notification-settings-view/NotificationSettingsView.tsx
  services/orchest-webserver/client/src/notification-settings-view/WebhookDocLink.tsx
  services/orchest-webserver/client/src/notification-settings-view/WebhookList.tsx
  services/orchest-webserver/client/src/notification-settings-view/WebhookVerifiedCheck.tsx
  services/orchest-webserver/client/src/notification-settings-view/common.ts
  services/orchest-webserver/client/src/notification-settings-view/create-webhook-dialog/CreateWebhookDialog.tsx
  services/orchest-webserver/client/src/notification-settings-view/create-webhook-dialog/WebhookUrlField.tsx
  services/orchest-webserver/client/src/notification-settings-view/create-webhook-dialog/useCreateWebhook.tsx
  services/orchest-webserver/client/src/notification-settings-view/create-webhook-dialog/useVerifyWebhookUrl.tsx
  services/orchest-webserver/client/src/notification-settings-view/notification-webhooks.ts
  services/orchest-webserver/client/src/notification-settings-view/useFetchNotificationEventTypes.tsx
  services/orchest-webserver/client/src/notification-settings-view/useFetchNotificationSubscribers.tsx
  services/orchest-webserver/client/src/notification-settings-view/useFetchSubscribedEventTypes.tsx
  services/orchest-webserver/client/src/notification-settings-view/useVerifyWebhook.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useInitializePipelineEditor.tsx
  services/orchest-webserver/client/src/routingConfig.tsx
  services/orchest-webserver/client/src/settings-view/SettingsView.tsx
Labels: new feature request

#1043 Fix file manager browsing on the read-only mode issue
  services/orchest-webserver/app/app/core/filemanager.py
  services/orchest-webserver/app/app/utils.py
  services/orchest-webserver/app/app/views/views.py
  services/orchest-webserver/client/src/components/ParamTree.tsx
  services/orchest-webserver/client/src/edit-job-view/LoadParametersDialog.tsx
  services/orchest-webserver/client/src/hooks/useCheckFileValidity.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/GenerateParametersDialog.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/PipelineSettingsView.tsx
  services/orchest-webserver/client/src/pipeline-view/PipelineStep.tsx
  services/orchest-webserver/client/src/pipeline-view/PipelineView.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileManager.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileManagerContext.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/common.tsx
  services/orchest-webserver/client/src/pipeline-view/step-details/StepDetailsContext.tsx
Labels: fix

#1024 Add support for loading job pipeline parameters with JSON files
  docs/source/fundamentals/jobs.rst
  pnpm-lock.yaml
  services/orchest-webserver/app/app/core/filemanager.py
  services/orchest-webserver/app/app/utils.py
  services/orchest-webserver/app/app/views/views.py
  services/orchest-webserver/client/src/components/FilePicker.tsx
  services/orchest-webserver/client/src/components/ParamTree.tsx
  services/orchest-webserver/client/src/components/ParameterEditor.tsx
  services/orchest-webserver/client/src/components/ProjectFilePicker.tsx
  services/orchest-webserver/client/src/edit-job-view/EditJobView.tsx
  services/orchest-webserver/client/src/edit-job-view/LoadParametersDialog.tsx
  services/orchest-webserver/client/src/edit-job-view/common.tsx
  services/orchest-webserver/client/src/hooks/useCheckFileValidity.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/GenerateParametersDialog.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/PipelineSettingsView.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/__tests__/useFetchPipelineSettings.test.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/common.ts
  services/orchest-webserver/client/src/pipeline-settings-view/useFetchPipelineSettings.ts
  services/orchest-webserver/client/src/pipeline-view/PipelineStep.tsx
  services/orchest-webserver/client/src/pipeline-view/PipelineView.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileManager.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileManagerContext.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/common.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineViewport.tsx
  services/orchest-webserver/client/src/pipeline-view/step-details/StepDetailsContext.tsx
  services/orchest-webserver/client/src/pipeline-view/step-details/StepDetailsProperties.tsx
  services/orchest-webserver/client/src/styles/main.scss
  services/orchest-webserver/client/src/types.d.ts
  services/orchest-webserver/client/src/utils/copyToClipboard.ts
  services/orchest-webserver/client/src/utils/isValidJson.ts
  services/orchest-webserver/client/src/utils/webserver-utils.ts
Labels: new feature request

#1047 Add more commands to Command Palette
  services/orchest-webserver/client/src/components/CommandPalette.tsx
  services/orchest-webserver/client/src/hooks/useMatchProjectRoot.ts
  services/orchest-webserver/client/src/routingConfig.tsx
Labels: improvement

#1016 Allow Orchest installation without installing Argo
  .github/workflows/do-release.yml
  docs/source/development/development_workflow.rst
  docs/source/getting_started/installation.rst
  orchest-cli/orchestcli/_version.py
  orchest-cli/orchestcli/cli.py
  orchest-cli/orchestcli/cmds.py
  services/orchest-controller/Makefile
  services/orchest-controller/cmd/controller/cmd/controller.go
  services/orchest-controller/deploy/examples/example-orchestcluster-without-argo.yaml
  services/orchest-controller/deploy/examples/example-orchestcluster-without-registry.yaml
  services/orchest-controller/deploy/helm/templates/_specs.tpl
  services/orchest-controller/deploy/helm/templates/deployment.yaml
  services/orchest-controller/deploy/helm/templates/orchest.io_orchestclusters.yaml
  services/orchest-controller/deploy/helm/values.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/.helmignore
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/Chart.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/README.md
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/README.md.gotmpl
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/ci/default-values.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/ci/enable-ingress-values.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/ci/enable-metrics-values.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/ci/enable-rbac-values.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/crds/argoproj.io_clusterworkflowtemplates.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/crds/argoproj.io_cronworkflows.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/crds/argoproj.io_workfloweventbindings.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/crds/argoproj.io_workflows.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/crds/argoproj.io_workflowtasksets.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/crds/argoproj.io_workflowtemplates.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/templates/NOTES.txt
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/templates/_helpers.tpl
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/templates/controller/workflow-aggregate-roles.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/templates/controller/workflow-controller-cluster-roles.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/templates/controller/workflow-controller-config-map.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/templates/controller/workflow-controller-crb.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/templates/controller/workflow-controller-deployment-pdb.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/templates/controller/workflow-controller-deployment.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/templates/controller/workflow-controller-sa.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/templates/controller/workflow-controller-service.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/templates/controller/workflow-controller-servicemonitor.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/templates/controller/workflow-rb.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/templates/controller/workflow-role.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/templates/controller/workflow-sa.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/templates/server/server-cluster-roles.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/templates/server/server-crb.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/templates/server/server-deployment-pdb.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/templates/server/server-deployment.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/templates/server/server-ingress.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/templates/server/server-sa.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/templates/server/server-service.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/helm/values.yaml
  services/orchest-controller/pkg/addons/addons.go
  services/orchest-controller/pkg/addons/helm_deployer.go
  services/orchest-controller/pkg/addons/path_deployer.go
  services/orchest-controller/pkg/apis/orchest/v1alpha1/types.go
  services/orchest-controller/pkg/apis/orchest/v1alpha1/zz_generated.deepcopy.go
  services/orchest-controller/pkg/controller/orchestcluster/cluster_controller.go
  services/orchest-controller/pkg/deployer/deployer_manager.go
  services/orchest-controller/pkg/helm/helm.go
  services/orchest-controller/pkg/utils/k8s_utils.go
Labels: improvement

#1041 Docs: enable `sphinx-hoverxref` on all references
  docs/requirements.txt
  docs/source/conf.py
Labels: improvement

#1051 Add system requirements to documentation
  docs/source/getting_started/installation.rst
Labels: improvement

#1062 Keep track of pipeline runs creation time at the database level
  services/orchest-api/app/app/models/_core.py
  services/orchest-api/app/app/schema.py
  services/orchest-api/app/migrations/versions/3433a9040ff4_.py
Labels: improvement

#1059 Extract PipelineEditorContextMenu from useContextMenu
  services/orchest-webserver/client/src/pipeline-view/PipelineStep.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useContextMenu.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineViewport.tsx
Labels: internal

#1072 Rework development workflow docs
  .github/pull_request_template.md
  docs/requirements.txt
  docs/source/conf.py
  docs/source/development/contributing.rst
  docs/source/development/development_workflow.md
  docs/source/development/development_workflow.rst
  docs/source/development/troubleshooting.rst
Labels: internal, documentation
