Repository orchest/orchest, pull requests merged in 2022-03, with the labels that each got.

#752 Upgrade JupyterLab to `v3.3.0`
  services/jupyter-server/requirements.txt
Labels: improvement

#767 Fix opening files in JupyterLab that contain uppercase characters in their name
  services/orchest-webserver/client/src/routingConfig.tsx
Labels: fix

#748 Remove jquery from pipeline editor and add minor UX improvements
  cypress/cypress/integration/interactive-runs.spec.ts
  cypress/cypress/integration/pipelines.spec.ts
  cypress/cypress/support/common.ts
  lib/javascript/utils/src/fetcher.ts
  pnpm-lock.yaml
  services/orchest-webserver/client/package.json
  services/orchest-webserver/client/src/App.tsx
  services/orchest-webserver/client/src/components/DataTable.tsx
  services/orchest-webserver/client/src/components/ProjectFilePicker.tsx
  services/orchest-webserver/client/src/hooks/useCheckFileValidity.tsx
  services/orchest-webserver/client/src/hooks/useFetchEnvironments.ts
  services/orchest-webserver/client/src/hooks/useForceUpdate.tsx
  services/orchest-webserver/client/src/job-view/JobView.tsx
  services/orchest-webserver/client/src/jupyter/Jupyter.tsx
  services/orchest-webserver/client/src/main.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/PipelineSettingsView.tsx
  services/orchest-webserver/client/src/pipeline-view/BackToJobButton.tsx
  services/orchest-webserver/client/src/pipeline-view/ConnectionDot.tsx
  services/orchest-webserver/client/src/pipeline-view/CreateNextStepButton.tsx
  services/orchest-webserver/client/src/pipeline-view/LogViewer.tsx
  services/orchest-webserver/client/src/pipeline-view/LogsView.tsx
  services/orchest-webserver/client/src/pipeline-view/PipelineActionButton.tsx
  services/orchest-webserver/client/src/pipeline-view/PipelineConnection.tsx
  services/orchest-webserver/client/src/pipeline-view/PipelineDetailsLogs.tsx
  services/orchest-webserver/client/src/pipeline-view/PipelineEditor.tsx
  services/orchest-webserver/client/src/pipeline-view/PipelineStep.tsx
  services/orchest-webserver/client/src/pipeline-view/PipelineView.tsx
  services/orchest-webserver/client/src/pipeline-view/__tests__/removeConnection.test.tsx
  services/orchest-webserver/client/src/pipeline-view/__tests__/willCreateCycle.test.tsx
  services/orchest-webserver/client/src/pipeline-view/common.tsx
  services/orchest-webserver/client/src/pipeline-view/contexts/PipelineCanvasContext.tsx
  services/orchest-webserver/client/src/pipeline-view/contexts/PipelineEditorContext.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useAutoStartSession.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useEventVars.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useFetchInteractiveRun.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useInitializePipelineEditor.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useInteractiveRuns.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useIsReadOnly.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/usePipelineCanvasState.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useSavingIndicator.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useSocketIO.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useStepExecutionState.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useZIndexMax.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-connection/ConnectionLine.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-connection/InteractiveConnection.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-connection/PipelineConnection.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-connection/common.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineCanvas.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineViewport.tsx
  services/orchest-webserver/client/src/pipeline-view/step-details/StepDetails.tsx
  services/orchest-webserver/client/src/pipeline-view/step-details/StepDetailsLogs.tsx
  services/orchest-webserver/client/src/pipeline-view/step-details/StepDetailsProperties.tsx
  services/orchest-webserver/client/src/styles/main.scss
  services/orchest-webserver/client/src/types.d.ts
  services/orchest-webserver/client/src/utils/jquery-replacement.ts
  services/orchest-webserver/client/src/utils/pipeline-layout.ts
  services/orchest-webserver/client/src/utils/resolve.ts
  services/orchest-webserver/client/src/utils/webserver-utils.ts
  services/orchest-webserver/client/src/views/FilePreviewView.tsx
Labels: improvement

#782 Fix highlighting navigation item "Jobs" when viewing the pipeline of a job run
  services/orchest-webserver/client/src/components/MainDrawer.tsx
  services/orchest-webserver/client/src/pipeline-view/CreateNextStepButton.tsx
Labels: fix

#783 Show Project Selector in deeper levels of the UI
  services/base-images/runnable-shared/runner/requirements-dev.txt
  services/orchest-webserver/client/src/components/HeaderBar.tsx
  services/orchest-webserver/client/src/components/MainDrawer.tsx
  services/orchest-webserver/client/src/components/ProjectSelector.tsx
  services/orchest-webserver/client/src/hooks/useMatchProjectRoot.ts
  services/orchest-webserver/client/src/routingConfig.tsx
Labels: improvement

#786 Enable debugger in JupyterLab
  services/base-images/runnable-shared/runner/requirements.txt
  services/orchest-webserver/app/app/res/kernels/docker/kernel.json
Labels: new feature request

#789 Decrease size of Python base image and the Enterprise Gateway image
  docs/source/fundamentals/environments.rst
  lib/python/orchest-internals/_orchest/internals/config.py
  services/base-images/base-kernel-julia/Dockerfile
  services/base-images/base-kernel-py-gpu/Dockerfile
  services/base-images/base-kernel-py/Dockerfile
  services/base-images/base-kernel-r/Dockerfile
  services/base-images/runnable-shared/bootscript.sh
  services/base-images/runnable-shared/runner/requirements-user.txt
  services/base-images/runnable-shared/runner/requirements.txt
  services/jupyter-enterprise-gateway/Dockerfile
  services/jupyter-server/Dockerfile
  services/jupyter-server/requirements.txt
  services/orchest-webserver/app/app/res/kernels/docker/kernel.json
Labels: improvement

#804 Fix zoom-in/out issue
  services/orchest-webserver/client/src/pipeline-view/PipelineEditor.tsx
Labels: fix

#809 Fix onboarding redirect to quickstart issue
  services/orchest-webserver/client/src/components/Layout/OnboardingDialog/OnboardingDialog.tsx
  services/orchest-webserver/client/src/components/Layout/OnboardingDialog/use-onboarding-dialog.ts
Labels: fix

#815 Fix the issue when saving services in pipeline editor
  services/orchest-webserver/client/src/hooks/useFetchPipelineJson.ts
  services/orchest-webserver/client/src/pipeline-settings-view/PipelineSettingsView.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/useFetchPipelineMetadata.ts
Labels: fix

#819 Fix showing onboarding dialog in help view
  services/orchest-webserver/client/src/components/Layout/OnboardingDialog/OnboardingDialog.tsx
  services/orchest-webserver/client/src/components/Layout/OnboardingDialog/use-onboarding-dialog.ts
  services/orchest-webserver/client/src/contexts/AppContext.tsx
Labels: fix

#828 add pvc to docker-registry
  deploy/Makefile
  deploy/README.md
  deploy/helm/charts/cluster-resources/charts/registry/templates/pvc.yaml
  services/orchest-ctl/app/cli/main.py
  services/orchest-ctl/app/connections.py
  services/orchest-ctl/app/orchest/__init__.py
  services/orchest-ctl/app/orchest/_core.py
  services/orchest-ctl/app/orchest/_k8s_wrapper.py
Labels: fix

#842 Enable panning and pinching on Pipeline Editor
  lib/design-system/package/package.json
  pnpm-lock.yaml
  services/auth-server/client/package.json
  services/orchest-webserver/client/package.json
  services/orchest-webserver/client/src/main.tsx
  services/orchest-webserver/client/src/pipeline-view/ConnectionDot.tsx
  services/orchest-webserver/client/src/pipeline-view/PipelineEditor.tsx
  services/orchest-webserver/client/src/pipeline-view/PipelineStep.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useEventVars.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-connection/PipelineConnection.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineViewport.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/useGestureOnViewport.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/useKeyboardEventsOnViewport.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/useMouseEventsOnViewport.tsx
Labels: improvement

#847 Fix the error when moving a folder while its sub folders or files are also selected
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileTree.tsx
Labels: fix
