Repository orchest/orchest, pull requests merged in 2022-04, with the labels that each got.

#832 Add development mode (internal use)
  deploy/helm/charts/orchest-webserver/templates/deployment.yaml
  docs/source/development/development_workflow.rst
  docs/source/development/how_orchest_works.rst
  docs/source/development/troubleshooting.rst
  scripts/build_container.sh
  scripts/build_image_in_minikube.sh
  scripts/install_minikube.sh
  scripts/redeploy_orchest_service_on_minikube.sh
  scripts/remove_image_from_minikube.sh
  scripts/remove_orchest_images.sh
  scripts/run_in_minikube.sh
  services/auth-server/app/app/__init__.py
  services/orchest-ctl/app/cli/main.py
  services/orchest-ctl/app/orchest/_core.py
  services/orchest-ctl/app/orchest/_k8s_wrapper.py
  services/orchest-ctl/app/utils.py
Labels: improvement, internal

#874 Allow increasing jobs and interactive runs parallelism without restarting Orchest
  services/orchest-api/app/app/utils.py
  services/orchest-api/app/config.py
Labels: improvement

#868 `orchest-api` owns the orchest settings
  docs/source/development/how_orchest_works.rst
  docs/source/fundamentals/configuration.rst
  lib/python/orchest-internals/_orchest/internals/utils.py
  services/auth-server/app/app/__init__.py
  services/auth-server/app/main.py
  services/orchest-api/app/app/__init__.py
  services/orchest-api/app/app/apis/namespace_ctl.py
  services/orchest-api/app/app/models.py
  services/orchest-api/app/app/schema.py
  services/orchest-api/app/app/utils.py
  services/orchest-api/app/config.py
  services/orchest-api/app/migrations/versions/39faa4822903_.py
  services/orchest-webserver/app/app/__init__.py
  services/orchest-webserver/app/app/views/views.py
Labels: improvement

#875 Automatically delete unused Orchest images from nodes
  services/node-agent/Dockerfile
  services/node-agent/app/image_deleter.py
  services/orchest-api/app/app/core/environments.py
  services/orchest-api/app/app/core/registry.py
Labels: improvement

#872 Automatically delete unused environment images from nodes and registry
  .github/pull_request_template.md
  deploy/Makefile
  deploy/helm/charts/celery-worker/templates/deployment.yaml
  deploy/helm/charts/orchest-api/templates/deployment.yaml
  deploy/helm/templates/_cluster-role.tpl
  lib/python/orchest-internals/_orchest/internals/config.py
  orchest-sdk/python/RELEASE-CHECKLIST.md
  scripts/build_container.sh
  services/node-agent/Dockerfile
  services/node-agent/app/image_deleter.py
  services/node-agent/app/image_puller.py
  services/node-agent/app/main.py
  services/node-agent/requirements.in
  services/node-agent/requirements.txt
  services/orchest-api/app/app/__init__.py
  services/orchest-api/app/app/apis/namespace_environment_image_builds.py
  services/orchest-api/app/app/apis/namespace_environment_images.py
  services/orchest-api/app/app/apis/namespace_environments.py
  services/orchest-api/app/app/apis/namespace_jupyter_image_builds.py
  services/orchest-api/app/app/apis/namespace_sessions.py
  services/orchest-api/app/app/core/environments.py
  services/orchest-api/app/app/core/jupyter_image_builds.py
  services/orchest-api/app/app/core/registry.py
  services/orchest-api/app/app/core/tasks.py
  services/orchest-api/app/app/errors.py
  services/orchest-api/app/app/models.py
  services/orchest-api/app/app/schema.py
  services/orchest-api/app/app/utils.py
  services/orchest-api/app/config.py
  services/orchest-api/app/migrations/versions/11539451f894_.py
  services/orchest-api/app/migrations/versions/21f4696fb7af_.py
  services/orchest-api/app/migrations/versions/4694f9241649_.py
  services/orchest-api/app/migrations/versions/7189e327c98a_.py
  services/orchest-api/app/migrations/versions/b5feeffd0ace_.py
  services/orchest-api/app/migrations/versions/da0cc2d95c2b_.py
  services/orchest-api/app/migrations/versions/f496e16be97c_.py
  services/orchest-webserver/app/app/res/kernels/launch_kubernetes.py
Labels: improvement

#886 Fix broken `update-sidecar` dependencies
  services/update-sidecar/requirements.in
  services/update-sidecar/requirements.txt
Labels: fix

#894 Fix broken Project Settings view
  services/orchest-webserver/client/src/routingConfig.tsx
  services/orchest-webserver/client/src/views/ProjectSettingsView.tsx
Labels: fix

#883 orchest-api scheduler keeps track of tasks in the database
  services/orchest-api/app/app/__init__.py
  services/orchest-api/app/app/core/scheduler.py
  services/orchest-api/app/app/models.py
  services/orchest-api/app/migrations/versions/6bbe0b4a8c4a_.py
Labels: improvement

#898 Fix Configure Jupyter Lab view not loading issue
  services/orchest-webserver/app/app/views/views.py
  services/orchest-webserver/client/src/hooks/useFetchPipelineJson.ts
  services/orchest-webserver/client/src/utils/webserver-utils.ts
  services/orchest-webserver/client/src/views/FilePreviewView.tsx
  services/orchest-webserver/client/src/views/JupyterLabView.tsx
Labels: fix

#892 Add project-not-found error
  services/orchest-webserver/client/src/components/ProjectBasedView.tsx
  services/orchest-webserver/client/src/components/ProjectSelector.tsx
  services/orchest-webserver/client/src/contexts/ProjectsContext.tsx
  services/orchest-webserver/client/src/contexts/__tests__/ProjectsContext.test.tsx
  services/orchest-webserver/client/src/hooks/useEnsureValidPipeline.tsx
  services/orchest-webserver/client/src/jobs-view/JobsView.tsx
  services/orchest-webserver/client/src/pipeline-view/PipelineView.tsx
  services/orchest-webserver/client/src/views/EnvironmentsView.tsx
Labels: improvement

#912 Fix failed to rename files in File Manager
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileTree.tsx
Labels: fix
