Repository orchest/orchest, pull requests merged in 2022-11, with the labels that each got.

#1401 New file picker, and various file state fixes
  services/orchest-webserver/client/src/api/files/fileApi.ts
  services/orchest-webserver/client/src/api/files/useFileApi.ts
  services/orchest-webserver/client/src/components/FilePicker.tsx
  services/orchest-webserver/client/src/components/PathBreadcrumbs.tsx
  services/orchest-webserver/client/src/components/ProjectFilePicker.tsx
  services/orchest-webserver/client/src/hooks/useFetchFileRoots.ts
  services/orchest-webserver/client/src/hooks/useUploader.ts
  services/orchest-webserver/client/src/jobs-view/job-view/LoadParametersDialog.tsx
  services/orchest-webserver/client/src/pipeline-view/common.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/ActionBar.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/CreateFileDialog.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/CreateFolderDialog.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileManager.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileManagerContext.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileManagerContextMenu.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileManagerLocalContext.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileTree.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileTreeRow.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/common.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/useCreateFile.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-canvas-header-bar/PipelineMoreOptionsMenu.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/NoScripts.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineViewport.tsx
  services/orchest-webserver/client/src/pipeline-view/step-details/StepProperties.tsx
  services/orchest-webserver/client/src/types.d.ts
  services/orchest-webserver/client/src/utils/file-map.ts
  services/orchest-webserver/client/src/utils/file.ts
  services/orchest-webserver/client/src/utils/path.ts
Labels: improvement

#1406 Make environment variables "secret" by default
  services/orchest-webserver/client/src/components/EnvVarInput.tsx
  services/orchest-webserver/client/src/components/EnvVarList.tsx
  services/orchest-webserver/client/src/jobs-view/job-view/EditJobEnvVariables.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/PipelineSettingsView.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/ServiceForm.tsx
  services/orchest-webserver/client/src/views/ProjectSettingsView.tsx
Labels: improvement

#1409 Replace "Unable to fetch sessions" alert with unintrusive snackbar message
  services/orchest-webserver/client/src/header-bar/HeaderBar.tsx
  services/orchest-webserver/client/src/header-bar/SessionStatus.tsx
  services/orchest-webserver/client/src/hooks/useSessionsPoller.ts
Labels: improvement

#1415 Fix can't view service under pipeline settings
  services/orchest-webserver/client/src/pipeline-settings-view/ServiceForm.tsx
Labels: fix

#1414 Do not assume non-root user in base env image
  services/orchest-api/app/app/core/environment_image_builds.py
Labels: fix

#1416 Update file tree when duplicating a file
  services/orchest-webserver/client/src/api/files/fileApi.ts
  services/orchest-webserver/client/src/api/files/useFileApi.ts
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileManagerContextMenu.tsx
Labels: fix

#1418 Fix/enable type checking in CI
  .github/workflows/ui.yml
  cypress/package.json
  lib/design-system/package/package.json
  lib/design-system/package/src/components/alert.tsx
  lib/design-system/package/src/components/icon-button.tsx
  lib/design-system/package/src/components/index.ts
  lib/design-system/package/src/core/config.ts
  lib/javascript/utils/package.json
  package.json
  pnpm-lock.yaml
  services/auth-server/client/package.json
  services/auth-server/client/src/App.tsx
  services/orchest-webserver/client/src/components/DataTable.tsx
  services/orchest-webserver/client/src/components/DescriptionList.tsx
  services/orchest-webserver/client/src/components/ParamTree.tsx
  services/orchest-webserver/client/src/hooks/useDragElementWithPosition.ts
  services/orchest-webserver/client/src/hooks/useUploader.ts
  services/orchest-webserver/client/src/jobs-view/common.tsx
  services/orchest-webserver/client/src/jobs-view/job-view/EditJobConfig.tsx
  services/orchest-webserver/client/src/notification-settings-view/NotificationEventsForm.tsx
  services/orchest-webserver/client/src/notification-settings-view/WebhookList.tsx
  services/orchest-webserver/client/src/notification-settings-view/notification-webhooks.ts
  services/orchest-webserver/client/src/pipeline-settings-view/PipelineParameters.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/PipelineSettingsView.tsx
  services/orchest-webserver/client/src/utils/record.ts
Labels: internal

#1419 Display "Changes not yet built" next to the setup script if there are local changes.
  services/orchest-webserver/client/src/environments-view/BuildEnvironmentButton.tsx
  services/orchest-webserver/client/src/environments-view/EnvironmentMenuList.tsx
  services/orchest-webserver/client/src/environments-view/EnvironmentMoreOptions.tsx
  services/orchest-webserver/client/src/environments-view/common.tsx
  services/orchest-webserver/client/src/environments-view/edit-environment/BaseImageRadioOption.tsx
  services/orchest-webserver/client/src/environments-view/edit-environment/BuildStatusAlert.tsx
  services/orchest-webserver/client/src/environments-view/edit-environment/EditEnvironmentName.tsx
  services/orchest-webserver/client/src/environments-view/edit-environment/EnvironmentImageBuildLogs.tsx
  services/orchest-webserver/client/src/environments-view/edit-environment/EnvironmentName.tsx
  services/orchest-webserver/client/src/environments-view/edit-environment/EnvironmentSetupScript.tsx
  services/orchest-webserver/client/src/environments-view/edit-environment/hooks/useLoadSelectedBaseImage.tsx
  services/orchest-webserver/client/src/environments-view/edit-environment/hooks/useSelectBaseImage.tsx
  services/orchest-webserver/client/src/environments-view/hooks/useSaveEnvironmentChanges.tsx
  services/orchest-webserver/client/src/environments-view/hooks/useSyncEnvironmentUuidWithQueryArgs.tsx
  services/orchest-webserver/client/src/environments-view/hooks/useUpdateBuildStatusInEnvironmentChanges.tsx
  services/orchest-webserver/client/src/environments-view/stores/useEditEnvironment.tsx
Labels: improvement

#1422 Log if a step file is not found during a run
  services/base-images/runnable-shared/runner/run.py
  services/base-images/runnable-shared/runner/runner/runners.py
Labels: improvement

#1423 Attempt to copy snapshot again in case of a project rename
  services/orchest-api/app/app/core/environment_image_builds.py
  services/orchest-api/app/app/core/tasks.py
Labels: fix

#1425 Fix: Make sure panel max width is based on current window width
  services/orchest-webserver/client/src/components/layout/MainSidePanel.tsx
  services/orchest-webserver/client/src/components/layout/stores/useLayoutStore.tsx
  services/orchest-webserver/client/src/pipeline-view/schedule-job/ScheduleJobPanel.tsx
  services/orchest-webserver/client/src/pipeline-view/step-details/StepDetails.tsx
Labels: fix

#1426 Reflow step logs on resize panel
  services/orchest-webserver/client/src/pipeline-view/LogViewer.tsx
Labels: fix

#1431 fix: Pipeline params got overwritten after closing Pipeline Settings panel.
  services/orchest-webserver/client/src/components/ParameterEditorWithJsonForm.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/PipelineSettingsView.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/__tests__/usePipelineSettings.test.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/hooks/useFetchPipelineSettingsData.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/hooks/usePipelineSettings.tsx
Labels: fix

#1433 Create a port name for each user service port
  services/orchest-api/app/app/core/sessions/_manifests.py
Labels: fix

#1436 fix: the response of FM read shouldn't be cached.
  services/orchest-webserver/app/app/views/views.py
Labels: fix

#1438 Support stopping starting sessions
  services/orchest-webserver/client/src/components/SessionToggleButton.tsx
Labels: improvement

#1439 Fix JupyterLab on mobile
  services/orchest-webserver/client/src/jupyter/Jupyter.tsx
Labels: fix

#1441 Make Orchest CLI package commands easier to use programmatically
  orchest-cli/orchestcli/_version.py
  orchest-cli/orchestcli/cli.py
  orchest-cli/orchestcli/cmds.py
  orchest-cli/orchestcli/utils.py
  services/orchest-api/app/app/apis/namespace_ctl.py
Labels: improvement, internal

#1442 Add setting to pause Orchest
  services/orchest-api/app/app/__init__.py
  services/orchest-api/app/app/apis/namespace_ctl.py
  services/orchest-api/app/app/core/scheduler.py
  services/orchest-api/app/app/utils.py
Labels: internal

#1444 Add support to specify node selector labels for the control and workers plane
  orchest-cli/orchestcli/_version.py
  orchest-cli/orchestcli/cli.py
  orchest-cli/orchestcli/cmds.py
  services/orchest-controller/deploy/helm/templates/deployment.yaml
  services/orchest-controller/deploy/helm/values.yaml
  services/orchest-controller/pkg/apis/orchest/v1alpha1/types.go
  services/orchest-controller/pkg/apis/orchest/v1alpha1/zz_generated.deepcopy.go
  services/orchest-controller/pkg/controller/orchestcluster/cluster_controller.go
  services/orchest-controller/pkg/controller/orchestcluster/cluster_utils.go
  services/orchest-controller/pkg/controller/orchestcomponent/auth_server.go
  services/orchest-controller/pkg/controller/orchestcomponent/buildkit_daemon.go
  services/orchest-controller/pkg/controller/orchestcomponent/celery_worker.go
  services/orchest-controller/pkg/controller/orchestcomponent/node_agent.go
  services/orchest-controller/pkg/controller/orchestcomponent/orchest_api.go
  services/orchest-controller/pkg/controller/orchestcomponent/orchest_database.go
  services/orchest-controller/pkg/controller/orchestcomponent/orchest_webserver.go
  services/orchest-controller/pkg/controller/orchestcomponent/rabbitmq_server.go
Labels: internal

#1449 Add option to back the user directory and Orchest state with different PVCs
  orchest-cli/orchestcli/cli.py
  orchest-cli/orchestcli/cmds.py
  services/orchest-api/celery_daemon_configs/worker_builds.conf
  services/orchest-api/celery_daemon_configs/worker_deliveries.conf
  services/orchest-api/celery_daemon_configs/worker_jobs.conf
  services/orchest-controller/cmd/controller/cmd/controller.go
  services/orchest-controller/pkg/apis/orchest/v1alpha1/types.go
  services/orchest-controller/pkg/apis/orchest/v1alpha1/zz_generated.deepcopy.go
  services/orchest-controller/pkg/controller/controller_utils.go
  services/orchest-controller/pkg/controller/orchestcluster/cluster_controller.go
  services/orchest-controller/pkg/controller/orchestcluster/cluster_utils.go
  services/orchest-controller/pkg/controller/orchestcomponent/celery_worker.go
  services/orchest-controller/pkg/controller/orchestcomponent/orchest_api.go
  services/orchest-controller/pkg/controller/orchestcomponent/orchest_database.go
  services/orchest-controller/pkg/controller/orchestcomponent/orchest_webserver.go
  services/orchest-controller/pkg/controller/orchestcomponent/rabbitmq_server.go
Labels: internal

#1451 Only consider `PENDING|STARTED` jobs for the `next_scheduled_job` query/endpoint
  services/orchest-api/app/app/apis/namespace_jobs.py
Labels: fix

#1453 Add starting/stopping indicators in sessions panel
  services/orchest-webserver/client/src/components/SessionToggleButton.tsx
  services/orchest-webserver/client/src/pipeline-view/sessions-panel/SessionsPanel.tsx
Labels: improvement
