Repository orchest/orchest, pull requests merged in 2022-08, with the labels that each got.

#1167 Get exit code to avoid race condition on failure
  services/orchest-api/app/app/core/image_utils.py
Labels: fix

#1169 Only remove helm histories if there is already a helm release
  services/orchest-controller/pkg/addons/helm_deployer.go
Labels: fix

#1178 Remove package managers builder cache
  services/orchest-api/app/app/core/image_utils.py
Labels: improvement

#1184 Improve race condition handling in image builds errors
  services/orchest-api/app/app/core/image_utils.py
Labels: improvement

#1186 Add endpoint to trigger a job run "manually"
  services/orchest-api/app/app/apis/namespace_jobs.py
  services/orchest-webserver/app/app/views/orchest_api.py
  services/orchest-webserver/client/src/job-view/JobView.tsx
Labels: improvement

#1192 Fix: peer dependency issue when building web server
  services/orchest-webserver/Dockerfile
Labels: fix

#1194 Add contribution documents
  CODE_OF_CONDUCT.md
  docs/source/development/contributing.md
  docs/source/development/contributing.rst
Labels: documentation

#1195 Remove `base-kernel-py-gpu` and `memory-server`
  .github/CODEOWNERS
  .github/workflows/docker-ci.yml
  .github/workflows/python-tests.yml
  docs/source/development/development_workflow.md
  lib/python/orchest-internals/_orchest/internals/config.py
  lib/python/orchest-internals/pyrightconfig.json
  orchest-sdk/python/orchest/_version.py
  orchest-sdk/python/orchest/transfer.py
  orchest-sdk/python/tests/test_transfer.py
  scripts/build-push-k8s-beta.sh
  scripts/build_container.sh
  scripts/run_tests.sh
  services/base-images/base-kernel-py-gpu/Dockerfile
  services/base-images/base-kernel-py-gpu/README.md
  services/memory-server/Dockerfile
  services/memory-server/README.md
  services/memory-server/app/config.py
  services/memory-server/app/main.py
  services/memory-server/app/manager.py
  services/memory-server/app/utils.py
  services/memory-server/pyrightconfig.json
  services/memory-server/requirements-dev.in
  services/memory-server/requirements-dev.txt
  services/memory-server/requirements.in
  services/memory-server/requirements.txt
  services/memory-server/tests/pipeline.json
  services/memory-server/tests/test_manager.py
  services/orchest-api/app/app/apis/namespace_sessions.py
  services/orchest-api/app/app/core/sessions/_core.py
  services/orchest-api/app/app/core/sessions/_manifests.py
  services/orchest-api/app/tests/namespaces/test_namespace_sessions.py
  services/orchest-webserver/app/app/views/orchest_api.py
  services/orchest-webserver/client/src/environment-edit-view/common.tsx
Labels: internal

#1166 Feature: Generate parameter forms from jsonschema
  docs/source/fundamentals/jobs.md
  docs/source/fundamentals/pipelines.md
  docs/source/img/parameter-schema.png
  pnpm-lock.yaml
  services/auth-server/client/package.json
  services/orchest-webserver/app/app/consts.py
  services/orchest-webserver/app/app/views/views.py
  services/orchest-webserver/client/package.json
  services/orchest-webserver/client/src/components/ParameterEditorWithJsonForm.tsx
  services/orchest-webserver/client/src/components/ParametersActions.tsx
  services/orchest-webserver/client/src/components/common/IconButton.tsx
  services/orchest-webserver/client/src/edit-job-view/common.tsx
  services/orchest-webserver/client/src/hooks/useCheckFileValidity.tsx
  services/orchest-webserver/client/src/hooks/useOpenSchemaFile.tsx
  services/orchest-webserver/client/src/hooks/useReadFile.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/PipelineParameters.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/PipelineSettingsView.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/__tests__/usePipelineSettings.test.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/hooks/useFetchPipelineSettingsData.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/hooks/useOpenPipelineSchemaFile.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/hooks/usePipelineEnvVariables.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/hooks/usePipelineProperty.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/hooks/usePipelineSettings.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/hooks/useReadPipelineSchemaFiles.tsx
  services/orchest-webserver/client/src/pipeline-view/step-details/NoJsonFormMessage.tsx
  services/orchest-webserver/client/src/pipeline-view/step-details/StepDetailsContext.tsx
  services/orchest-webserver/client/src/pipeline-view/step-details/StepDetailsProperties.tsx
  services/orchest-webserver/client/src/pipeline-view/step-details/StepParameters.tsx
  services/orchest-webserver/client/src/pipeline-view/step-details/useOpenStepSchemaFile.tsx
  services/orchest-webserver/client/src/theme.ts
  services/orchest-webserver/client/src/types.d.ts
  services/orchest-webserver/client/src/utils/__tests__/path.test.tsx
  services/orchest-webserver/client/src/utils/path.ts
Labels: improvement

#1200 Add instructions on setting up a reverse proxy
  docs/source/getting_started/installation.md
Labels: improvement, documentation

#1202 Change docs to PyData theme
  docs/requirements.txt
  docs/source/_static/css/custom_styles.css
  docs/source/_static/css/installer_widget.css
  docs/source/_static/css/rate_widget.css
  docs/source/_static/js/algolia.js
  docs/source/_static/js/rate_widget.js
  docs/source/_templates/layout.html
  docs/source/_templates/search-field.html
  docs/source/conf.py
  docs/source/development/index.md
  docs/source/fundamentals/index.md
  docs/source/getting_started/index.md
  docs/source/index.md
  docs/source/reference/index.md
Labels: improvement

#1203 Remove Argo Server
  services/orchest-controller/deploy/thirdparty/argo-workflows/orchest-values.yaml
  userdir/.gitignore
  userdir/.orchest/database/.gitignore
  userdir/.orchest/kernels/.gitignore
  userdir/.orchest/rabbitmq-mnesia/.gitignore
  userdir/.orchest/user-configurations/jupyterlab/.gitignore
  userdir/.orchest/user-configurations/jupyterlab/lab/.gitignore
  userdir/.orchest/user-configurations/jupyterlab/user-settings/.gitignore
  userdir/README.md
  userdir/data/.gitignore
  userdir/jobs/.gitignore
  userdir/projects/.gitignore
Labels: internal

#1204 UI Overhaul: Improve pipeline editor performance
  services/orchest-webserver/client/src/components/ResizablePane.tsx
  services/orchest-webserver/client/src/hooks/useDragElementWithPosition.ts
  services/orchest-webserver/client/src/hooks/useForceUpdate.tsx
  services/orchest-webserver/client/src/pipeline-view/CreateStepButton.tsx
  services/orchest-webserver/client/src/pipeline-view/PipelineEditor.tsx
  services/orchest-webserver/client/src/pipeline-view/PipelineStep.tsx
  services/orchest-webserver/client/src/pipeline-view/SelectionRectangle.tsx
  services/orchest-webserver/client/src/pipeline-view/action-helpers/eventVarsHelpers.ts
  services/orchest-webserver/client/src/pipeline-view/common.tsx
  services/orchest-webserver/client/src/pipeline-view/contexts/CanvasScalingContext.tsx
  services/orchest-webserver/client/src/pipeline-view/contexts/PipelineCanvasContext.tsx
  services/orchest-webserver/client/src/pipeline-view/contexts/PipelineContextProviders.tsx
  services/orchest-webserver/client/src/pipeline-view/contexts/PipelineRefsContext.tsx
  services/orchest-webserver/client/src/pipeline-view/contexts/ScaleFactorContext.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/DragIndicator.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileManagerContextMenu.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileManagerLocalContext.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useCreateStep.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/usePipelineCanvasState.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/usePipelineUiState.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-connection/InteractiveConnection.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-connection/PipelineConnection.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-connection/common.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineViewport.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineViewportContextMenu.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/hooks/useViewportGestures.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/hooks/useViewportKeyboardEvents.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/hooks/useViewportMouseEvents.tsx
  services/orchest-webserver/client/src/pipeline-view/zoom-controls/ZoomValueField.tsx
  services/orchest-webserver/client/src/styles/main.scss
  services/orchest-webserver/client/src/types.d.ts
  services/orchest-webserver/client/src/utils/element.ts
  services/orchest-webserver/client/src/utils/geometry.ts
  services/orchest-webserver/client/src/utils/jquery-replacement.ts
  services/orchest-webserver/client/src/utils/mouse.ts
Labels: improvement

#1205 Allow using custom image for orchest components
  docs/source/development/implementation_details.md
  services/orchest-controller/pkg/apis/orchest/v1alpha1/types.go
  services/orchest-controller/pkg/apis/orchest/v1alpha1/zz_generated.deepcopy.go
  services/orchest-controller/pkg/controller/orchestcluster/cluster_controller.go
  services/orchest-controller/pkg/controller/orchestcluster/cluster_utils.go
  services/orchest-controller/pkg/controller/orchestcluster/cluster_utils_test.go
Labels: improvement

#1215 Add docs logos for dark and light themes
  docs/source/_static/img/logo-dark.png
  docs/source/_static/img/logo-light.png
  docs/source/conf.py
  docs/source/img/logo.png
Labels: documentation

#1183 Pass version as command line to controller
  .dockerignore
  services/orchest-controller/Dockerfile
  services/orchest-controller/Makefile
  services/orchest-controller/deploy/helm/templates/deployment.yaml
  services/orchest-controller/deploy/helm/values.yaml
Labels: internal

#1234 Fix unable to save pipeline parameters when clicking outside of the field.
  services/orchest-webserver/client/src/components/ParameterEditorWithJsonForm.tsx
  services/orchest-webserver/client/src/pipeline-view/step-details/StepParameters.tsx
Labels: fix
