Repository orchest/orchest, pull requests merged in 2022-12, with the labels that each got.

#1454 Add an optional EFS CSI deployment to the Orchest installation
  orchest-cli/orchestcli/cli.py
  orchest-cli/orchestcli/cmds.py
  services/orchest-controller/deploy/thirdparty/efs-csi-driver/helm/.helmignore
  services/orchest-controller/deploy/thirdparty/efs-csi-driver/helm/CHANGELOG.md
  services/orchest-controller/deploy/thirdparty/efs-csi-driver/helm/Chart.yaml
  services/orchest-controller/deploy/thirdparty/efs-csi-driver/helm/templates/NOTES.txt
  services/orchest-controller/deploy/thirdparty/efs-csi-driver/helm/templates/_helpers.tpl
  services/orchest-controller/deploy/thirdparty/efs-csi-driver/helm/templates/controller-deployment.yaml
  services/orchest-controller/deploy/thirdparty/efs-csi-driver/helm/templates/controller-serviceaccount.yaml
  services/orchest-controller/deploy/thirdparty/efs-csi-driver/helm/templates/csidriver.yaml
  services/orchest-controller/deploy/thirdparty/efs-csi-driver/helm/templates/node-daemonset.yaml
  services/orchest-controller/deploy/thirdparty/efs-csi-driver/helm/templates/node-serviceaccount.yaml
  services/orchest-controller/deploy/thirdparty/efs-csi-driver/helm/templates/storageclass.yaml
  services/orchest-controller/deploy/thirdparty/efs-csi-driver/helm/values.yaml
  services/orchest-controller/deploy/thirdparty/efs-csi-driver/orchest-values.yaml
  services/orchest-controller/pkg/addons/addons.go
  services/orchest-controller/pkg/addons/helm_deployer.go
  services/orchest-controller/pkg/controller/orchestcluster/cluster_controller.go
  services/orchest-controller/pkg/controller/orchestcluster/cluster_utils.go
Labels: internal

#1456 Detect cluster nodes readiness when scheduling pods
  services/orchest-api/app/app/core/pod_scheduling.py
Labels: improvement, internal

#1459 Fix job parameter rendering issues
  services/orchest-webserver/client/src/jobs-view/job-view/EditJobParameters.tsx
Labels: fix

#1462 Fix: schemas not loading
  services/orchest-webserver/app/app/views/views.py
Labels: fix

#1469 Internal - multi node and customized volumes support
  orchest-cli/orchestcli/_version.py
  orchest-cli/orchestcli/cli.py
  orchest-cli/orchestcli/cmds.py
  services/orchest-api/app/app/apis/namespace_ctl.py
  services/orchest-api/app/app/apis/namespace_environment_image_builds.py
  services/orchest-api/app/app/apis/namespace_environment_images.py
  services/orchest-api/app/app/apis/namespace_jupyter_image_builds.py
  services/orchest-api/app/app/core/image_utils.py
  services/orchest-api/app/app/core/pod_scheduling.py
  services/orchest-api/app/app/core/tasks.py
  services/orchest-api/app/config.py
  services/orchest-api/celery_daemon_configs/worker_builds.conf
  services/orchest-api/celery_daemon_configs/worker_deliveries.conf
  services/orchest-api/celery_daemon_configs/worker_jobs.conf
  services/orchest-controller/cmd/controller/cmd/controller.go
  services/orchest-controller/deploy/helm/templates/deployment.yaml
  services/orchest-controller/deploy/helm/values.yaml
  services/orchest-controller/deploy/thirdparty/efs-csi-driver/helm/.helmignore
  services/orchest-controller/deploy/thirdparty/efs-csi-driver/helm/CHANGELOG.md
  services/orchest-controller/deploy/thirdparty/efs-csi-driver/helm/Chart.yaml
  services/orchest-controller/deploy/thirdparty/efs-csi-driver/helm/templates/NOTES.txt
  services/orchest-controller/deploy/thirdparty/efs-csi-driver/helm/templates/_helpers.tpl
  services/orchest-controller/deploy/thirdparty/efs-csi-driver/helm/templates/controller-deployment.yaml
  services/orchest-controller/deploy/thirdparty/efs-csi-driver/helm/templates/controller-serviceaccount.yaml
  services/orchest-controller/deploy/thirdparty/efs-csi-driver/helm/templates/csidriver.yaml
  services/orchest-controller/deploy/thirdparty/efs-csi-driver/helm/templates/node-daemonset.yaml
  services/orchest-controller/deploy/thirdparty/efs-csi-driver/helm/templates/node-serviceaccount.yaml
  services/orchest-controller/deploy/thirdparty/efs-csi-driver/helm/templates/storageclass.yaml
  services/orchest-controller/deploy/thirdparty/efs-csi-driver/helm/values.yaml
  services/orchest-controller/deploy/thirdparty/efs-csi-driver/orchest-values.yaml
  services/orchest-controller/pkg/addons/addons.go
  services/orchest-controller/pkg/addons/helm_deployer.go
  services/orchest-controller/pkg/apis/orchest/v1alpha1/types.go
  services/orchest-controller/pkg/apis/orchest/v1alpha1/zz_generated.deepcopy.go
  services/orchest-controller/pkg/controller/controller_utils.go
  services/orchest-controller/pkg/controller/orchestcluster/cluster_controller.go
  services/orchest-controller/pkg/controller/orchestcluster/cluster_utils.go
  services/orchest-controller/pkg/controller/orchestcomponent/auth_server.go
  services/orchest-controller/pkg/controller/orchestcomponent/buildkit_daemon.go
  services/orchest-controller/pkg/controller/orchestcomponent/celery_worker.go
  services/orchest-controller/pkg/controller/orchestcomponent/node_agent.go
  services/orchest-controller/pkg/controller/orchestcomponent/orchest_api.go
  services/orchest-controller/pkg/controller/orchestcomponent/orchest_database.go
  services/orchest-controller/pkg/controller/orchestcomponent/orchest_webserver.go
  services/orchest-controller/pkg/controller/orchestcomponent/rabbitmq_server.go
  services/orchest-webserver/app/app/views/views.py
Labels: internal

#1475 Fix bad "open" link next to pipeline selector
  services/orchest-webserver/client/src/pipeline-view/file-preview/StepPipelineSelector.tsx
Labels: fix

#1477 Fix double-click issues in the file browser
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileManager.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileTree.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileTreeRow.tsx
Labels: fix

#1480 Remove unnecessary filter when listing images on node using docker container runtime
  services/node-agent/app/container_runtime.py
Labels: fix

#1484 Move Orchest configs to a zustand store
  services/orchest-webserver/client/src/App.tsx
  services/orchest-webserver/client/src/api/system-config/orchestConfigsApi.ts
  services/orchest-webserver/client/src/api/system-config/useOrchestConfigsApi.ts
  services/orchest-webserver/client/src/contexts/GlobalContext.tsx
  services/orchest-webserver/client/src/contexts/Intercom.tsx
  services/orchest-webserver/client/src/contexts/Providers.tsx
  services/orchest-webserver/client/src/environments-view/edit-environment/CustomImageDetails.tsx
  services/orchest-webserver/client/src/environments-view/edit-environment/EnvironmentImageBuildLogs.tsx
  services/orchest-webserver/client/src/environments-view/hooks/useCreateEnvironment.tsx
  services/orchest-webserver/client/src/header-bar/HeaderBar.tsx
  services/orchest-webserver/client/src/hooks/useFetchOrchestConfigs.ts
  services/orchest-webserver/client/src/hooks/useHideIntercom.tsx
  services/orchest-webserver/client/src/hooks/useInitIntercom.ts
  services/orchest-webserver/client/src/hooks/useOnAppStart.ts
  services/orchest-webserver/client/src/hooks/useOpenReplay.ts
  services/orchest-webserver/client/src/hooks/useSendAnalyticEvent.ts
  services/orchest-webserver/client/src/jobs-view/job-view/hooks/useParameterReservedKey.tsx
  services/orchest-webserver/client/src/settings-view/SettingsView.tsx
  services/orchest-webserver/client/src/types.d.ts
  services/orchest-webserver/client/src/views/ConfigureJupyterLabView.tsx
  services/orchest-webserver/client/src/views/HelpView.tsx
Labels: internal

#1483 Fix workers plane scheduling
  services/orchest-api/app/app/core/pod_scheduling.py
  services/orchest-api/app/app/core/sessions/_manifests.py
Labels: fix

#1487 Don't redirect to or display "project" on settings/help
  services/orchest-webserver/client/src/routingConfig.tsx
Labels: fix

#1488 New status system
  services/orchest-webserver/client/src/api/files/useFileApi.ts
  services/orchest-webserver/client/src/components/Status.tsx
  services/orchest-webserver/client/src/components/common/StatusIcon.tsx
  services/orchest-webserver/client/src/components/common/SystemStatusChip.tsx
  services/orchest-webserver/client/src/components/common/SystemStatusIcon.tsx
  services/orchest-webserver/client/src/environments-view/BuildStatusIcon.tsx
  services/orchest-webserver/client/src/environments-view/EnvironmentMenuItem.tsx
  services/orchest-webserver/client/src/environments-view/edit-environment/BuildStatusAlert.tsx
  services/orchest-webserver/client/src/hooks/useFileStatus.ts
  services/orchest-webserver/client/src/hooks/usePollBackgroundTask.ts
  services/orchest-webserver/client/src/hooks/useStepFileStatus.ts
  services/orchest-webserver/client/src/jobs-view/JobMenuItem.tsx
  services/orchest-webserver/client/src/jobs-view/JobStatusIcon.tsx
  services/orchest-webserver/client/src/jobs-view/job-view/JobRunsTable.tsx
  services/orchest-webserver/client/src/jobs-view/job-view/JobStatusAlert.tsx
  services/orchest-webserver/client/src/jobs-view/job-view/JobStatusIcon.tsx
  services/orchest-webserver/client/src/pipeline-view/ConnectionDot.tsx
  services/orchest-webserver/client/src/pipeline-view/PipelineEditor.tsx
  services/orchest-webserver/client/src/pipeline-view/PipelineStep.tsx
  services/orchest-webserver/client/src/pipeline-view/StepExecutionState.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useStepFile.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-connection/ConnectionLine.tsx
  services/orchest-webserver/client/src/projects-view/hooks/useGitImport.ts
  services/orchest-webserver/client/src/styles/main.scss
  services/orchest-webserver/client/src/types.d.ts
  services/orchest-webserver/client/src/utils/file-map.ts
  services/orchest-webserver/client/src/utils/system-status.ts
Labels: improvement

#1489 Move git import background task to orchest api
  services/orchest-api/Dockerfile_celery
  services/orchest-api/app/app/apis/__init__.py
  services/orchest-api/app/app/apis/namespace_git_imports.py
  services/orchest-api/app/app/core/tasks.py
  services/orchest-api/app/app/errors.py
  services/orchest-api/app/app/models/__init__.py
  services/orchest-api/app/app/models/_core.py
  services/orchest-api/app/app/schema.py
  services/orchest-api/app/app/utils.py
  services/orchest-api/app/config.py
  services/orchest-api/app/migrations/versions/68591a046415_.py
  services/orchest-api/celery_daemon_configs/worker_other_tasks.conf
  services/orchest-webserver/app/app/__init__.py
  services/orchest-webserver/app/app/core/projects.py
  services/orchest-webserver/app/app/models.py
  services/orchest-webserver/app/app/schemas.py
  services/orchest-webserver/app/app/views/background_tasks.py
  services/orchest-webserver/app/app/views/views.py
  services/orchest-webserver/app/migrations/versions/5581eb626bb2_.py
  services/orchest-webserver/app/scripts/background_tasks.py
  services/orchest-webserver/client/src/api/background-tasks/backgroundTasksApi.ts
  services/orchest-webserver/client/src/api/git-imports/gitImportsApi.ts
  services/orchest-webserver/client/src/api/git-imports/useGitImportsApi.ts
  services/orchest-webserver/client/src/hooks/usePollBackgroundTask.ts
  services/orchest-webserver/client/src/hooks/usePollGitImport.ts
  services/orchest-webserver/client/src/projects-view/ImportDialog.tsx
  services/orchest-webserver/client/src/projects-view/hooks/useGitImport.ts
  services/orchest-webserver/client/src/types.d.ts
Labels: internal

#1492 Add pipeline setting to limit step level parallelism
  lib/python/orchest-internals/_orchest/internals/compat.py
  services/orchest-api/app/app/core/pipeline_runs.py
  services/orchest-api/app/app/core/pod_scheduling.py
  services/orchest-api/app/app/types.py
  services/orchest-webserver/app/app/utils.py
  services/orchest-webserver/client/src/pipeline-settings-view/PipelineSettingsView.tsx
  services/orchest-webserver/client/src/types.d.ts
  services/orchest-webserver/client/src/utils/pipeline-schema.ts
Labels: new feature request
