Repository orchest/orchest, pull requests merged in 2022-10, with the labels that each got.

#1320 Sticky header shadows and unify layout components
  services/orchest-webserver/client/src/App.tsx
  services/orchest-webserver/client/src/components/Layout/index.ts
  services/orchest-webserver/client/src/components/Layout/layout-with-side-panel/LayoutWithSidePanel.tsx
  services/orchest-webserver/client/src/components/Layout/layout-with-side-panel/MainContainer.tsx
  services/orchest-webserver/client/src/components/common/StatusIcon.tsx
  services/orchest-webserver/client/src/components/layout/CenteredStack.tsx
  services/orchest-webserver/client/src/components/layout/Layout.tsx
  services/orchest-webserver/client/src/components/layout/MainSidePanel.tsx
  services/orchest-webserver/client/src/components/layout/ScrollPane.tsx
  services/orchest-webserver/client/src/components/layout/SidePanelMenuItem.tsx
  services/orchest-webserver/client/src/components/layout/StickyHeader.tsx
  services/orchest-webserver/client/src/components/layout/ViewLayout.tsx
  services/orchest-webserver/client/src/components/layout/legacy/OnboardingDialog/OnboardingDialog.tsx
  services/orchest-webserver/client/src/components/layout/legacy/OnboardingDialog/OnboardingDialogCarousel/OnboardingDialogCarousel.tsx
  services/orchest-webserver/client/src/components/layout/legacy/OnboardingDialog/OnboardingDialogCarousel/content.ts
  services/orchest-webserver/client/src/components/layout/legacy/OnboardingDialog/OnboardingDialogCarousel/index.ts
  services/orchest-webserver/client/src/components/layout/legacy/OnboardingDialog/OnboardingDialogCarousel/use-onboarding-dialog-carousel.ts
  services/orchest-webserver/client/src/components/layout/legacy/OnboardingDialog/assets.tsx
  services/orchest-webserver/client/src/components/layout/legacy/OnboardingDialog/index.ts
  services/orchest-webserver/client/src/components/layout/legacy/OnboardingDialog/types.d.ts
  services/orchest-webserver/client/src/components/layout/legacy/OnboardingDialog/use-onboarding-dialog.ts
  services/orchest-webserver/client/src/components/layout/stores/useLayoutStore.tsx
  services/orchest-webserver/client/src/environments-view/BuildStatusIcon.tsx
  services/orchest-webserver/client/src/environments-view/EnvironmentHeader.tsx
  services/orchest-webserver/client/src/environments-view/EnvironmentMenuItem.tsx
  services/orchest-webserver/client/src/environments-view/EnvironmentsView.tsx
  services/orchest-webserver/client/src/environments-view/edit-environment/EditEnvironment.tsx
  services/orchest-webserver/client/src/jobs-view/JobMenuItem.tsx
  services/orchest-webserver/client/src/jobs-view/JobStatusIcon.tsx
  services/orchest-webserver/client/src/jobs-view/JobsView.tsx
  services/orchest-webserver/client/src/jobs-view/job-view/JobHeader.tsx
  services/orchest-webserver/client/src/jobs-view/job-view/JobStatusIcon.tsx
  services/orchest-webserver/client/src/jobs-view/job-view/JobView.tsx
  services/orchest-webserver/client/src/notification-settings-view/NotificationSettingsView.tsx
  services/orchest-webserver/client/src/pipeline-view/PipelineView.tsx
  services/orchest-webserver/client/src/pipeline-view/ReadOnlyBanner.tsx
  services/orchest-webserver/client/src/pipeline-view/schedule-job/ScheduleJobPanel.tsx
  services/orchest-webserver/client/src/pipeline-view/step-details/StepDetails.tsx
  services/orchest-webserver/client/src/projects-view/ProjectsHeader.tsx
  services/orchest-webserver/client/src/projects-view/ProjectsTabs.tsx
  services/orchest-webserver/client/src/projects-view/ProjectsView.tsx
  services/orchest-webserver/client/src/projects-view/TempLayout.tsx
  services/orchest-webserver/client/src/settings-view/SettingsView.tsx
  services/orchest-webserver/client/src/views/ConfigureJupyterLabView.tsx
  services/orchest-webserver/client/src/views/FilePreviewView.tsx
  services/orchest-webserver/client/src/views/HelpView.tsx
  services/orchest-webserver/client/src/views/JobRunView.tsx
  services/orchest-webserver/client/src/views/JupyterLabView.tsx
  services/orchest-webserver/client/src/views/ManageUsersView.tsx
  services/orchest-webserver/client/src/views/ProjectSettingsView.tsx
  services/orchest-webserver/client/src/views/UpdateView.tsx
Labels: improvement, internal

#1327 Fix: incorrect warning after saving a recurring Job.
  services/orchest-webserver/client/src/jobs-view/job-view/JobPrimaryButtons.tsx
  services/orchest-webserver/client/src/jobs-view/job-view/hooks/useJobActions.tsx
Labels: fix

#1322 Improve step selector performance
  services/orchest-webserver/client/src/pipeline-view/PipelineStep.tsx
  services/orchest-webserver/client/src/pipeline-view/contexts/CanvasScalingContext.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/usePipelineUiState.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineViewport.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/hooks/useViewportMouseEvents.tsx
Labels: improvement, internal

#1333 Fix race condition between job scheduler and job cancellation
  services/orchest-api/app/app/apis/namespace_jobs.py
  services/orchest-api/app/app/core/scheduler.py
Labels: fix

#1337 Move log-streamer to its own container in webserver pod
  services/orchest-controller/pkg/controller/orchestcomponent/orchest_webserver.go
  services/orchest-webserver/app/app/__init__.py
  services/orchest-webserver/app/scripts/log_streamer.py
Labels: fix

#1335 Use `-exec ... +` notation for `find` to copy build context
  services/orchest-api/app/app/core/environment_image_builds.py
Labels: improvement

#1341 Don't concurrently push or pull images
  services/node-agent/app/container_runtime.py
  services/node-agent/app/image_deleter.py
  services/node-agent/app/image_puller.py
  services/node-agent/app/image_pusher.py
Labels: improvement

#1340 Add retries to k8s python sdk
  orchest-cli/orchestcli/cmds.py
  services/orchest-api/app/app/connections.py
Labels: internal

#1344 Right align ellipsis menu in projects table
  services/orchest-webserver/client/src/projects-view/ProjectsTable.tsx
Labels: fix

#1345 Change copy to "import complete" instead of "upload complete"
  services/orchest-webserver/client/src/projects-view/ImportDialog.tsx
Labels: fix

#1342 Fix: Environment build logs sometimes are failed to render.
  services/orchest-webserver/app/app/socketio_server.py
  services/orchest-webserver/client/src/components/ImageBuildLog.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useSocketIO.tsx
Labels: fix

#1346 Tweak CPU resource requests
  services/orchest-controller/pkg/controller/orchestcomponent/celery_worker.go
  services/orchest-controller/pkg/controller/orchestcomponent/orchest_api.go
Labels: improvement

#1343 Docker desktop installation docs
  docs/source/_static/js/installer_widget.js
  services/orchest-controller/pkg/controller/orchestcluster/cluster_utils.go
  services/orchest-controller/pkg/utils/k8s_utils.go
Labels: documentation

#1334 Support scrolling horizontally in the pipeline editor when holding Shift
  docs/source/reference/shortcuts.md
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/hooks/useViewportGestures.tsx
Labels: improvement

#1348 Indicate that the setup script can't be edited on build
  services/orchest-webserver/client/src/components/common/CodeMirror.tsx
  services/orchest-webserver/client/src/environments-view/edit-environment/EnvironmentSetupScript.tsx
Labels: improvement

#1336 Fix "cancel job run" does not get disabled when run finishes
  services/orchest-webserver/client/src/api/job-runs/useJobRunsApi.ts
  services/orchest-webserver/client/src/api/pipeline-runs/pipelineRunsApi.ts
  services/orchest-webserver/client/src/components/common/ErrorSummary.tsx
  services/orchest-webserver/client/src/hooks/useActiveJobRun.ts
  services/orchest-webserver/client/src/hooks/useActivePipelineRun.ts
  services/orchest-webserver/client/src/hooks/useCancelJobRun.ts
  services/orchest-webserver/client/src/hooks/useCancelJobRun.tsx
  services/orchest-webserver/client/src/hooks/useFetchActivePipelineRun.tsx
  services/orchest-webserver/client/src/hooks/useInterval.ts
  services/orchest-webserver/client/src/jobs-view/job-view/JobRunsTable.tsx
  services/orchest-webserver/client/src/pipeline-view/PipelineStep.tsx
  services/orchest-webserver/client/src/pipeline-view/StepExecutionState.tsx
  services/orchest-webserver/client/src/pipeline-view/common.tsx
  services/orchest-webserver/client/src/pipeline-view/contexts/InteractiveRunsContext.tsx
  services/orchest-webserver/client/src/pipeline-view/contexts/PipelineContextProviders.tsx
  services/orchest-webserver/client/src/pipeline-view/contexts/PipelineDataContext.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useFetchInteractiveRun.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useInteractiveRuns.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/usePipelineRuns.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useStepExecutionState.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-canvas-header-bar/ServicesMenu.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-canvas-header-bar/primary-action/CancelJobRunButton.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-canvas-header-bar/primary-action/PipelineOperationButtonIcon.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-canvas-header-bar/primary-action/RunPipelineButton.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-canvas-header-bar/primary-action/usePipelineActions.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-canvas-header-bar/useServices.ts
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineViewportContextMenu.tsx
  services/orchest-webserver/client/src/store/scoped.ts
  services/orchest-webserver/client/src/utils/error.ts
  services/orchest-webserver/client/src/utils/pipeline.ts
  services/orchest-webserver/client/src/utils/record.ts
Labels: internal, fix

#1352 Fix UpdateJobPipelineRun deadlock
  services/orchest-api/app/app/apis/namespace_jobs.py
Labels: fix

#1351 Dispose of existing celery db connections post fork
  services/orchest-api/app/app/apis/namespace_jobs.py
  services/orchest-api/app/app/core/tasks.py
Labels: fix

#1357 Fix: Duplicated Environment build logs when switching browser tabs.
  services/orchest-webserver/client/src/components/ImageBuildLog.tsx
  services/orchest-webserver/client/src/environments-view/edit-environment/EnvironmentImageBuildLogs.tsx
Labels: fix

#1359 fix: Hide Intercom when the side panel or a Snackbar appears.
  services/orchest-webserver/client/src/components/common/SnackBar.tsx
  services/orchest-webserver/client/src/hooks/useHideIntercom.tsx
  services/orchest-webserver/client/src/jobs-view/job-view/WebhookHint.tsx
  services/orchest-webserver/client/src/pipeline-view/schedule-job/ScheduleJob.tsx
  services/orchest-webserver/client/src/pipeline-view/schedule-job/ScheduleJobSnackBar.tsx
  services/orchest-webserver/client/src/views/ConfigureJupyterLabView.tsx
Labels: improvement

#1362 Set the `body-size` to `0` in ingress resources
  services/orchest-controller/pkg/controller/orchestcomponent/component_utils.go
Labels: fix

#1355 Celery-worker updates the status of pipeline runs and steps without passing through the `orchest-api`.
  services/orchest-api/app/app/apis/namespace_jobs.py
  services/orchest-api/app/app/apis/namespace_runs.py
  services/orchest-api/app/app/core/pipeline_runs.py
  services/orchest-api/app/app/core/pipelines.py
  services/orchest-api/app/app/core/tasks.py
  services/orchest-api/app/app/types.py
  services/orchest-api/app/app/utils.py
  services/orchest-api/app/tests/test_pipeline_execution_order.py
Labels: internal

#1366 fix: Header should be hidden if no items available in Environments and Jobs
  services/orchest-webserver/client/src/environments-view/EnvironmentsView.tsx
  services/orchest-webserver/client/src/jobs-view/JobsView.tsx
Labels: improvement

#1370 Do not persist base image version by default
  lib/python/orchest-internals/_orchest/internals/config.py
  services/orchest-webserver/client/src/environments-view/edit-environment/hooks/useLoadSelectedBaseImage.tsx
  services/orchest-webserver/client/src/environments-view/edit-environment/hooks/useSelectBaseImage.tsx
Labels: fix

#1367 Cypress: Navigation
  cypress/cypress/integration/auth.spec.ts
  cypress/cypress/integration/file-system-interactions.spec.ts
  cypress/cypress/integration/interactive-runs.spec.ts
  cypress/cypress/integration/jobs.spec.ts
  cypress/cypress/integration/pipelines.spec.ts
  cypress/cypress/integration/projects.spec.ts
  cypress/cypress/integration/services.spec.ts
  cypress/cypress/support/commands.ts
  cypress/cypress/support/common.ts
  services/orchest-webserver/client/src/header-bar/NavigationTabs.tsx
  services/orchest-webserver/client/src/project-selector/GoToExamplesButton.tsx
  services/orchest-webserver/client/src/project-selector/ProjectSelectorMenu.tsx
  services/orchest-webserver/client/src/project-selector/ProjectSelectorToggle.tsx
  services/orchest-webserver/client/src/projects-view/ProjectList.tsx
Labels: internal

#1375 fix: Jupyter Image doesn't build if active sessions.
  services/orchest-webserver/client/src/components/ImageBuildStatus.tsx
  services/orchest-webserver/client/src/components/legacy/LegacyImageBuildLog.tsx
  services/orchest-webserver/client/src/types.d.ts
  services/orchest-webserver/client/src/views/ConfigureJupyterLabView.tsx
Labels: fix

#1378 Fix bad step offset being set when zoomed out and moving steps
  services/orchest-webserver/client/src/pipeline-view/PipelineStep.tsx
Labels: fix

#1380 Cypress: Projects
  cypress/cypress/integration/projects.spec.ts
  cypress/cypress/support/commands.ts
  cypress/cypress/support/common.ts
  scripts/run_integration_tests.sh
  services/orchest-webserver/client/src/components/DataTable.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/PipelineSettingsView.tsx
  services/orchest-webserver/client/src/project-selector/ProjectSelectorMenu.tsx
  services/orchest-webserver/client/src/projects-view/CreateProjectDialog.tsx
  services/orchest-webserver/client/src/projects-view/ImportDialog.tsx
  services/orchest-webserver/client/src/projects-view/ImportSuccessDialog.tsx
  services/orchest-webserver/client/src/projects-view/NoProject.tsx
  services/orchest-webserver/client/src/projects-view/ProjectList.tsx
  services/orchest-webserver/client/src/projects-view/ProjectsHeader.tsx
  services/orchest-webserver/client/src/projects-view/ProjectsTable.tsx
Labels: internal

#1373 Offset pipeline starting position if read-only banner is showing
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineViewport.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/hooks/useViewportKeyboardEvents.tsx
Labels: improvement

#1383 Remove body size limit from jupyter server ingress
  services/orchest-api/app/app/core/sessions/_manifests.py
Labels: fix

#1388 Fix: The file tree can't be expanded beyond the third level
  services/orchest-webserver/client/src/pipeline-view/file-manager/CreateFileDialog.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/CreateFolderDialog.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileManager.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileManagerContext.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileTree.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/common.tsx
  services/orchest-webserver/client/src/utils/path.ts
Labels: fix

#1392 fix: Incorrect warning bout "Project doesn't exist"
  services/orchest-webserver/client/src/projects-view/ProjectsTable.tsx
Labels: fix

#1393 fix: Redundant warning about Environment building in progress.
  services/orchest-webserver/client/src/contexts/ProjectsContext.tsx
Labels: fix

#1397 Set empty string as default file path when creating new step
  services/orchest-webserver/client/src/pipeline-view/file-manager/common.tsx
Labels: improvement

#1399 Fail Project import if repo couldn't be `clone`d
  services/orchest-webserver/app/scripts/background_tasks.py
  services/orchest-webserver/client/src/projects-view/ImportDialog.tsx
  services/orchest-webserver/client/src/projects-view/hooks/useImportGitRepo.ts
  services/orchest-webserver/client/src/utils/webserver-utils.ts
Labels: improvement
