Repository orchest/orchest, pull requests merged in 2022-07, with the labels that each got.

#1076 Fix celery-worker bringup and image builder on arm64
  services/orchest-api/app/config.py
  services/orchest-api/start_celery_daemon.sh
Labels: fix

#1073 Support multiple client sessions per user
  services/auth-server/app/app/models.py
  services/auth-server/app/app/views.py
  services/auth-server/app/config.py
  services/auth-server/app/migrations/versions/9376105c8654_.py
  services/auth-server/app/migrations/versions/fe9a960dc117_.py
Labels: improvement

#1079 Allow specifying volume claim sizes on `orchest install`
  orchest-cli/orchestcli/_version.py
  orchest-cli/orchestcli/cli.py
  orchest-cli/orchestcli/cmds.py
  services/orchest-controller/deploy/helm/templates/orchest.io_orchestclusters.yaml
  services/orchest-controller/pkg/apis/orchest/v1alpha1/types.go
  services/orchest-controller/pkg/controller/orchestcluster/cluster_controller.go
Labels: improvement

#1074 Periodically cleanup builder cache
  services/orchest-api/app/app/apis/namespace_ctl.py
  services/orchest-api/app/app/core/image_utils.py
  services/orchest-api/app/app/core/scheduler.py
  services/orchest-api/app/app/core/tasks.py
  services/orchest-api/app/config.py
Labels: improvement

#1048 Support `containerd` as the container runtime
  .github/workflows/docker-ci.yml
  docs/source/_static/css/installer_widget.css
  docs/source/_static/js/installer_widget.js
  docs/source/conf.py
  docs/source/getting_started/install-widget.html
  docs/source/getting_started/installation.rst
  lib/python/orchest-internals/_orchest/internals/config.py
  lib/python/orchest-internals/_orchest/internals/utils.py
  orchest-cli/orchestcli/_version.py
  orchest-cli/orchestcli/cli.py
  orchest-cli/orchestcli/cmds.py
  scripts/build_container.sh
  services/node-agent/Dockerfile
  services/node-agent/app/container_runtime.py
  services/node-agent/app/image_deleter.py
  services/node-agent/app/image_puller.py
  services/orchest-api/app/app/core/pipelines.py
  services/orchest-api/app/app/core/sessions/_manifests.py
  services/orchest-api/app/app/utils.py
  services/orchest-controller/deploy/examples/example-orchestcluster-microk8s.yaml
  services/orchest-controller/deploy/thirdparty/argo-workflows/orchest-values.yaml
  services/orchest-controller/go.mod
  services/orchest-controller/go.sum
  services/orchest-controller/pkg/controller/controller_utils.go
  services/orchest-controller/pkg/controller/orchestcluster/cluster_controller.go
  services/orchest-controller/pkg/controller/orchestcluster/cluster_utils.go
  services/orchest-controller/pkg/controller/orchestcomponent/auth_server.go
  services/orchest-controller/pkg/controller/orchestcomponent/component_utils.go
  services/orchest-controller/pkg/controller/orchestcomponent/node_agent.go
  services/orchest-controller/pkg/controller/orchestcomponent/orchest_api.go
  services/orchest-controller/pkg/controller/orchestcomponent/orchest_webserver.go
  services/orchest-controller/pkg/utils/k8s_utils.go
  services/orchest-webserver/app/app/res/kernels/launch_kubernetes.py
  tools/image-puller/Dockerfile
  tools/image-puller/pull_image.sh
Labels: new feature request

#1096 Mount jupyterlab settings directory in image builder when building custom jupyter images
  services/orchest-api/app/app/core/image_utils.py
  services/orchest-api/app/app/core/jupyter_image_builds.py
Labels: improvement

#1087 Fix web server request logging in dev mode
  README.md
  services/orchest-api/app/app/__init__.py
  services/orchest-webserver/app/app/__init__.py
Labels: fix

#1100 Autofocus the parameter edit field in Job Edit view.
  services/orchest-webserver/client/src/components/ParameterEditor.tsx
Labels: improvement

#1102 Fix: a rebased branch cannot be re-deployed.
  scripts/redeploy_branch.sh
Labels: internal

#1093 Set correct permissions on `/pip-cache`
  services/orchest-api/app/app/core/image_utils.py
Labels: improvement

#1099 Only use `image-puller` `initContainer` if `jupyter-server` is customized by user
  lib/python/orchest-internals/_orchest/internals/utils.py
  services/orchest-api/app/app/core/sessions/_manifests.py
  services/orchest-api/app/app/utils.py
Labels: improvement

#1097 Create pipeline step on file creation
  lib/javascript/utils/src/fetcher.ts
  lib/javascript/utils/src/typed.ts
  pnpm-lock.yaml
  services/orchest-webserver/client/package.json
  services/orchest-webserver/client/src/.wdyr.ts
  services/orchest-webserver/client/src/components/FilePicker.tsx
  services/orchest-webserver/client/src/components/ProjectFilePicker.tsx
  services/orchest-webserver/client/src/environment-edit-view/CustomImageDialog.tsx
  services/orchest-webserver/client/src/environment-edit-view/EnvironmentEditView.tsx
  services/orchest-webserver/client/src/hooks/useCheckFileValidity.tsx
  services/orchest-webserver/client/src/pipeline-view/CreateNextStepButton.tsx
  services/orchest-webserver/client/src/pipeline-view/CreateStepButton.tsx
  services/orchest-webserver/client/src/pipeline-view/PipelineEditor.tsx
  services/orchest-webserver/client/src/pipeline-view/contexts/PipelineEditorContext.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/ActionBar.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/CreateFileDialog.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/CreateFolderDialog.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileManagerLocalContext.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileTree.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/common.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/useCreateFile.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useCreateStep.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineViewport.tsx
  services/orchest-webserver/client/src/styles/main.scss
Labels: improvement

#1110 Include OS specific instructions in CLI
  orchest-cli/orchestcli/_version.py
  orchest-cli/orchestcli/cmds.py
Labels: improvement

#1112 Refactor SessionContext and AppContext.
  services/orchest-webserver/app/app/views/orchest_api.py
  services/orchest-webserver/client/src/components/BuildPendingDialog.tsx
  services/orchest-webserver/client/src/components/SessionToggleButton.tsx
  services/orchest-webserver/client/src/contexts/AppContext.tsx
  services/orchest-webserver/client/src/contexts/ProjectsContext.tsx
  services/orchest-webserver/client/src/contexts/SessionsContext.tsx
  services/orchest-webserver/client/src/environments-view/common.tsx
  services/orchest-webserver/client/src/hooks/useSessionsPoller.ts
  services/orchest-webserver/client/src/job-view/JobView.tsx
  services/orchest-webserver/client/src/jobs-view/JobList.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/PipelineSettingsView.tsx
  services/orchest-webserver/client/src/pipeline-view/LogsView.tsx
  services/orchest-webserver/client/src/pipeline-view/contexts/PipelineEditorContext.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileTree.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/TreeItem.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useAutoStartSession.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useIsReadOnly.tsx
  services/orchest-webserver/client/src/pipeline-view/sessions-panel/SessionsPanel.tsx
  services/orchest-webserver/client/src/types.d.ts
  services/orchest-webserver/client/src/utils/webserver-utils.ts
  services/orchest-webserver/client/src/views/JupyterLabView.tsx
Labels: internal

#1114 fix: JupyterLab stuck when session already exists
  services/orchest-webserver/client/src/views/JupyterLabView.tsx
Labels: internal

#1113 Improve `Development` documents structure
  docs/source/development/appendix.md
  docs/source/development/concepts_in_orchest.md
  docs/source/development/feature_manuals.rst
  docs/source/development/how_orchest_works.rst
  docs/source/development/implementation_best_practices.rst
  docs/source/development/implementation_details.md
  docs/source/fundamentals/glossary.md
  docs/source/img/concepts/Environments.png
  docs/source/img/concepts/Files.png
  docs/source/img/concepts/Job.png
  docs/source/img/concepts/Pipeline.png
  docs/source/img/concepts/Project.png
  docs/source/img/concepts/Step.png
  docs/source/index.rst
Labels: internal

#1118 Fix `Run selected steps` in the context menu not working issue.
  services/orchest-webserver/client/src/pipeline-view/PipelineEditor.tsx
  services/orchest-webserver/client/src/pipeline-view/PipelineStep.tsx
  services/orchest-webserver/client/src/pipeline-view/contexts/PipelineEditorContext.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useContextMenu.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineViewport.tsx
Labels: fix

#1117 Improve `orchest-cli` loading spinner robustness
  orchest-cli/orchestcli/cli.py
  orchest-cli/orchestcli/cmds.py
Labels: improvement

#1116 Add rating widget, fix sidebar scrollbar issue.
  docs/source/_static/css/custom_styles.css
  docs/source/_static/css/rate_widget.css
  docs/source/_static/js/installer_widget.js
  docs/source/_static/js/rate_widget.js
  docs/source/conf.py
Labels: improvement

#1115 File editor improvements
  lib/javascript/utils/src/typed.ts
  services/orchest-webserver/client/src/components/FilePicker.tsx
  services/orchest-webserver/client/src/hooks/useClickOutside.ts
  services/orchest-webserver/client/src/hooks/useOnClickOutside.ts
  services/orchest-webserver/client/src/pipeline-view/common.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/DragIndicator.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileManager.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileManagerContextMenu.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileManagerLocalContext.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileTree.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileTreeContainer.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/TreeItem.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/TreeRow.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/common.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/useCreateFile.tsx
  services/orchest-webserver/client/src/utils/element.ts
Labels: improvement

#1123 Pass detected ingress class name to orchest-api
  services/orchest-api/app/app/core/sessions/_manifests.py
  services/orchest-controller/pkg/controller/orchestcomponent/node_agent.go
  services/orchest-controller/pkg/controller/orchestcomponent/orchest_api.go
  services/orchest-controller/pkg/utils/k8s_utils.go
Labels: improvement, fix

#1130 fix: show a Snackbar when stopping all sessions.
  services/orchest-webserver/client/src/views/ConfigureJupyterLabView.tsx
Labels: fix

#1132 Fix Javascript errors in docs by correctly handling `READTHEDOCS_DATA`
  docs/source/_static/js/rate_widget.js
Labels: fix

#1135 Improve path abstractions
  lib/javascript/utils/src/typed.ts
  services/orchest-webserver/client/src/components/FilePicker.tsx
  services/orchest-webserver/client/src/components/ProjectFilePicker.tsx
  services/orchest-webserver/client/src/hooks/useCheckFileValidity.tsx
  services/orchest-webserver/client/src/pipeline-view/PipelineEditor.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/DragIndicator.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileManagerContextMenu.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileManagerLocalContext.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileTree.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/TreeRow.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/__tests__/getRelativePathTo.test.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/common.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useCreateStep.tsx
  services/orchest-webserver/client/src/pipeline-view/step-details/StepDetailsProperties.tsx
  services/orchest-webserver/client/src/utils/__tests__/path.test.tsx
  services/orchest-webserver/client/src/utils/path.ts
  services/orchest-webserver/client/src/utils/webserver-utils.ts
  services/orchest-webserver/client/src/views/JupyterLabView.tsx
Labels: internal

#1141 Fix error on environments page
  services/orchest-webserver/client/src/pipeline-view/hooks/useAutoStartSession.tsx
Labels: fix

#1134 Fix Flask services' performance issues on Windows
  .gitignore
  lib/python/orchest-internals/_orchest/internals/utils.py
  pnpm-lock.yaml
  scripts/run_pip_compile.sh
  services/auth-server/requirements.in
  services/auth-server/requirements.txt
  services/auth-server/start.sh
  services/orchest-api/requirements-dev.in
  services/orchest-api/requirements-dev.txt
  services/orchest-api/requirements.in
  services/orchest-api/requirements.txt
  services/orchest-api/start.sh
  services/orchest-webserver/client/package.json
  services/orchest-webserver/requirements.in
  services/orchest-webserver/requirements.txt
  services/orchest-webserver/start.sh
Labels: improvement, fix

#1144 Add version warning for latest docs
  docs/requirements.txt
  docs/source/conf.py
Labels: improvement

#1126 Update third-parties on Orchest update
  services/orchest-controller/deploy/thirdparty/docker-registry/orchest-values.yaml
  services/orchest-controller/pkg/addons/addons.go
  services/orchest-controller/pkg/addons/helm_deployer.go
  services/orchest-controller/pkg/addons/path_deployer.go
  services/orchest-controller/pkg/controller/controller_utils.go
  services/orchest-controller/pkg/controller/orchestcluster/cluster_controller.go
  services/orchest-controller/pkg/controller/orchestcluster/cluster_utils.go
  services/orchest-controller/pkg/controller/orchestcomponent/auth_server.go
  services/orchest-controller/pkg/controller/orchestcomponent/celery_worker.go
  services/orchest-controller/pkg/controller/orchestcomponent/component_utils.go
  services/orchest-controller/pkg/controller/orchestcomponent/node_agent.go
  services/orchest-controller/pkg/controller/orchestcomponent/orchest_api.go
  services/orchest-controller/pkg/controller/orchestcomponent/orchest_database.go
  services/orchest-controller/pkg/controller/orchestcomponent/orchest_webserver.go
  services/orchest-controller/pkg/controller/orchestcomponent/rabbitmq_server.go
  services/orchest-controller/pkg/helm/builder.go
  services/orchest-controller/pkg/helm/helm.go
  services/orchest-controller/pkg/utils/util.go
Labels: improvement
