Repository orchest/orchest, pull requests merged in 2022-05, with the labels that each got.

#904 Add recurring task to process deliveries
  deploy/helm/charts/celery-worker/templates/deployment.yaml
  services/orchest-api/Dockerfile_celery
  services/orchest-api/app/app/core/notifications/__init__.py
  services/orchest-api/app/app/core/notifications/webhooks.py
  services/orchest-api/app/app/core/scheduler.py
  services/orchest-api/app/app/core/tasks.py
  services/orchest-api/app/app/models.py
  services/orchest-api/app/config.py
  services/orchest-api/celery_daemon_configs/worker_deliveries.conf
Labels: improvement

#902 Add Webhooks logic to `orchest-api`
  deploy/helm/charts/celery-worker/templates/deployment.yaml
  services/orchest-api/Dockerfile_celery
  services/orchest-api/app/app/apis/namespace_notifications.py
  services/orchest-api/app/app/core/events.py
  services/orchest-api/app/app/core/notifications/__init__.py
  services/orchest-api/app/app/core/notifications/utils.py
  services/orchest-api/app/app/core/notifications/webhooks.py
  services/orchest-api/app/app/core/scheduler.py
  services/orchest-api/app/app/core/tasks.py
  services/orchest-api/app/app/errors.py
  services/orchest-api/app/app/models.py
  services/orchest-api/app/app/schema.py
  services/orchest-api/app/config.py
  services/orchest-api/app/migrations/versions/01dd57800cfc_.py
  services/orchest-api/app/migrations/versions/ff549d6b66be_.py
  services/orchest-api/celery_daemon_configs/worker_deliveries.conf
  services/orchest-api/requirements.in
  services/orchest-api/requirements.txt
Labels: improvement

#905 Expand webhook payload content
  services/orchest-api/app/app/apis/namespace_jobs.py
  services/orchest-api/app/app/apis/namespace_notifications.py
  services/orchest-api/app/app/apis/namespace_projects.py
  services/orchest-api/app/app/core/events.py
  services/orchest-api/app/app/core/notifications/utils.py
  services/orchest-api/app/app/core/notifications/webhooks.py
  services/orchest-api/app/app/models.py
  services/orchest-api/app/app/schema.py
  services/orchest-api/app/migrations/versions/00ed420c6abf_.py
  services/orchest-api/app/migrations/versions/7b9a23ad5946_.py
  services/orchest-api/app/migrations/versions/dfe5c529e6da_.py
  services/orchest-webserver/app/app/core/projects.py
  services/orchest-webserver/app/app/views/views.py
  services/orchest-webserver/client/src/job-view/JobStatus.tsx
  services/orchest-webserver/client/src/types.d.ts
Labels: improvement

#920 Keep current tab selected on editor when selecting a different step
  services/orchest-webserver/client/src/pipeline-view/hooks/useEventVars.tsx
  services/orchest-webserver/client/src/pipeline-view/step-details/StepDetails.tsx
Labels: improvement

#918 Move analytics module to the shared internal library
  lib/python/orchest-internals/_orchest/internals/analytics.py
  lib/python/orchest-internals/_orchest/internals/config.py
  lib/python/orchest-internals/setup.py
  services/orchest-webserver/app/app/__init__.py
  services/orchest-webserver/app/app/config.py
  services/orchest-webserver/app/app/core/scheduler.py
  services/orchest-webserver/app/app/views/analytics.py
  services/orchest-webserver/app/app/views/orchest_api.py
  services/orchest-webserver/app/app/views/views.py
  services/orchest-webserver/requirements.in
  services/orchest-webserver/requirements.txt
Labels: improvement

#712 Gate the session toggle
  lib/javascript/utils/src/fetcher.ts
  services/orchest-webserver/client/src/components/BuildPendingDialog.tsx
  services/orchest-webserver/client/src/components/SessionToggleButton.tsx
  services/orchest-webserver/client/src/contexts/Providers.tsx
  services/orchest-webserver/client/src/contexts/SessionsContext.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useAutoStartSession.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useIsReadOnly.tsx
  services/orchest-webserver/client/src/types.d.ts
  services/orchest-webserver/client/src/utils/webserver-utils.ts
  services/orchest-webserver/client/src/views/JupyterLabView.tsx
Labels: improvement

#962 Add environment created/delete events to `orchest-api` (notifications)
  lib/python/orchest-internals/_orchest/internals/analytics.py
  services/orchest-api/app/app/apis/namespace_environments.py
  services/orchest-api/app/app/core/events.py
  services/orchest-api/app/app/models.py
  services/orchest-api/app/migrations/versions/19ce7297c194_.py
Labels: improvement, internal

#961 Move job_update event to the `orchest-api` (notifications)
  lib/python/orchest-internals/_orchest/internals/analytics.py
  services/orchest-api/app/app/apis/namespace_environments.py
  services/orchest-api/app/app/apis/namespace_jobs.py
  services/orchest-api/app/app/core/events.py
  services/orchest-api/app/app/core/notifications/analytics.py
  services/orchest-api/app/app/models.py
  services/orchest-api/app/migrations/versions/19ce7297c194_.py
  services/orchest-api/app/migrations/versions/a4b1f48ddab5.py
  services/orchest-webserver/app/app/views/orchest_api.py
Labels: improvement, internal

#953 Add interactive pipeline run events to `orchest-api` (notifications)
  lib/python/orchest-internals/_orchest/internals/analytics.py
  scripts/migration_manager.sh
  services/orchest-api/app/app/apis/namespace_environments.py
  services/orchest-api/app/app/apis/namespace_jobs.py
  services/orchest-api/app/app/apis/namespace_pipelines.py
  services/orchest-api/app/app/apis/namespace_projects.py
  services/orchest-api/app/app/apis/namespace_runs.py
  services/orchest-api/app/app/core/events.py
  services/orchest-api/app/app/core/notifications/analytics.py
  services/orchest-api/app/app/models.py
  services/orchest-api/app/app/schema.py
  services/orchest-api/app/app/types.py
  services/orchest-api/app/app/utils.py
  services/orchest-api/app/migrations/versions/19ce7297c194_.py
  services/orchest-api/app/migrations/versions/23def7128481_.py
  services/orchest-api/app/migrations/versions/268b3e08cb46_.py
  services/orchest-api/app/migrations/versions/2b573339900f_.py
  services/orchest-api/app/migrations/versions/637920f5715f_.py
  services/orchest-api/app/migrations/versions/a4b1f48ddab5.py
  services/orchest-api/app/migrations/versions/a863be01327d_.py
  services/orchest-webserver/app/app/utils.py
  services/orchest-webserver/app/app/views/orchest_api.py
Labels: improvement, internal

#950 Add jupyter builds and interactive sessions events to `orchest-api` (notifications)
  lib/python/orchest-internals/_orchest/internals/analytics.py
  scripts/migration_manager.sh
  services/orchest-api/app/app/apis/namespace_environments.py
  services/orchest-api/app/app/apis/namespace_jobs.py
  services/orchest-api/app/app/apis/namespace_jupyter_image_builds.py
  services/orchest-api/app/app/apis/namespace_pipelines.py
  services/orchest-api/app/app/apis/namespace_projects.py
  services/orchest-api/app/app/apis/namespace_runs.py
  services/orchest-api/app/app/apis/namespace_sessions.py
  services/orchest-api/app/app/core/events.py
  services/orchest-api/app/app/core/jupyter_image_builds.py
  services/orchest-api/app/app/core/notifications/analytics.py
  services/orchest-api/app/app/models.py
  services/orchest-api/app/app/schema.py
  services/orchest-api/app/app/types.py
  services/orchest-api/app/app/utils.py
  services/orchest-api/app/migrations/versions/19ce7297c194_.py
  services/orchest-api/app/migrations/versions/23def7128481_.py
  services/orchest-api/app/migrations/versions/268b3e08cb46_.py
  services/orchest-api/app/migrations/versions/2b573339900f_.py
  services/orchest-api/app/migrations/versions/637920f5715f_.py
  services/orchest-api/app/migrations/versions/849b7b154ef6_.py
  services/orchest-api/app/migrations/versions/a4b1f48ddab5.py
  services/orchest-api/app/migrations/versions/a863be01327d_.py
  services/orchest-api/app/migrations/versions/ad0b4cda3e50_.py
  services/orchest-webserver/app/app/utils.py
  services/orchest-webserver/app/app/views/orchest_api.py
Labels: improvement, internal

#947 Give orchest api access to the analytics module
  .pre-commit-config.yaml
  lib/python/orchest-internals/_orchest/internals/analytics.py
  lib/python/orchest-internals/_orchest/internals/utils.py
  scripts/migration_manager.sh
  services/orchest-api/app/app/__init__.py
  services/orchest-api/app/app/apis/namespace_environments.py
  services/orchest-api/app/app/apis/namespace_jobs.py
  services/orchest-api/app/app/apis/namespace_jupyter_image_builds.py
  services/orchest-api/app/app/apis/namespace_notifications.py
  services/orchest-api/app/app/apis/namespace_pipelines.py
  services/orchest-api/app/app/apis/namespace_projects.py
  services/orchest-api/app/app/apis/namespace_runs.py
  services/orchest-api/app/app/apis/namespace_sessions.py
  services/orchest-api/app/app/core/events.py
  services/orchest-api/app/app/core/jupyter_image_builds.py
  services/orchest-api/app/app/core/notifications/__init__.py
  services/orchest-api/app/app/core/notifications/analytics.py
  services/orchest-api/app/app/core/tasks.py
  services/orchest-api/app/app/models.py
  services/orchest-api/app/app/schema.py
  services/orchest-api/app/app/types.py
  services/orchest-api/app/app/utils.py
  services/orchest-api/app/migrations/versions/19ce7297c194_.py
  services/orchest-api/app/migrations/versions/23def7128481_.py
  services/orchest-api/app/migrations/versions/268b3e08cb46_.py
  services/orchest-api/app/migrations/versions/2b573339900f_.py
  services/orchest-api/app/migrations/versions/4e2dcbcaf213_.py
  services/orchest-api/app/migrations/versions/637920f5715f_.py
  services/orchest-api/app/migrations/versions/785f9995f297_.py
  services/orchest-api/app/migrations/versions/849b7b154ef6_.py
  services/orchest-api/app/migrations/versions/a4b1f48ddab5.py
  services/orchest-api/app/migrations/versions/a863be01327d_.py
  services/orchest-api/app/migrations/versions/ad0b4cda3e50_.py
  services/orchest-webserver/app/app/utils.py
  services/orchest-webserver/app/app/views/orchest_api.py
  services/orchest-webserver/app/app/views/views.py
  services/orchest-webserver/client/src/components/SystemDialog.tsx
  services/orchest-webserver/client/src/edit-job-view/EditJobView.tsx
  services/orchest-webserver/client/src/environment-edit-view/EnvironmentEditView.tsx
  services/orchest-webserver/client/src/hooks/useSendAnalyticEvent.ts
  services/orchest-webserver/client/src/job-view/JobView.tsx
  services/orchest-webserver/client/src/jobs-view/JobsView.tsx
  services/orchest-webserver/client/src/pipeline-settings-view/PipelineSettingsView.tsx
  services/orchest-webserver/client/src/pipeline-view/LogsView.tsx
  services/orchest-webserver/client/src/pipeline-view/PipelineView.tsx
  services/orchest-webserver/client/src/projects-view/ExamplesView.tsx
  services/orchest-webserver/client/src/projects-view/ProjectsView.tsx
  services/orchest-webserver/client/src/settings-view/SettingsView.tsx
  services/orchest-webserver/client/src/views/ConfigureJupyterLabView.tsx
  services/orchest-webserver/client/src/views/EnvironmentsView.tsx
  services/orchest-webserver/client/src/views/FilePreviewView.tsx
  services/orchest-webserver/client/src/views/HelpView.tsx
  services/orchest-webserver/client/src/views/JobRunView.tsx
  services/orchest-webserver/client/src/views/JupyterLabView.tsx
  services/orchest-webserver/client/src/views/ManageUsersView.tsx
  services/orchest-webserver/client/src/views/NotFound.tsx
  services/orchest-webserver/client/src/views/ProjectSettingsView.tsx
  services/orchest-webserver/client/src/views/UpdateView.tsx
Labels: improvement

#949 Persist the last-viewed pipeline in the project.
  pnpm-lock.yaml
  services/orchest-webserver/client/jest.setup.js
  services/orchest-webserver/client/package.json
  services/orchest-webserver/client/src/components/DataTable.tsx
  services/orchest-webserver/client/src/contexts/ProjectsContext.tsx
  services/orchest-webserver/client/src/contexts/__tests__/useAutoFetchPipelines.test.tsx
  services/orchest-webserver/client/src/contexts/useAutoFetchPipelines.tsx
  services/orchest-webserver/client/src/hooks/__tests__/useEnsureValidPipeline.test.tsx
  services/orchest-webserver/client/src/hooks/useAsync.ts
  services/orchest-webserver/client/src/hooks/useCheckUpdate.tsx
  services/orchest-webserver/client/src/hooks/useCustomRoute.ts
  services/orchest-webserver/client/src/hooks/useEnsureValidPipeline.tsx
  services/orchest-webserver/client/src/hooks/useFetchPipelineJson.ts
  services/orchest-webserver/client/src/hooks/useFetchPipelines.ts
  services/orchest-webserver/client/src/hooks/useHasChanged.tsx
  services/orchest-webserver/client/src/hooks/useLastSeenPipeline.ts
  services/orchest-webserver/client/src/hooks/useLocalStorage.ts
  services/orchest-webserver/client/src/pipeline-settings-view/__tests__/useFetchPipelineSettings.test.tsx
  services/orchest-webserver/client/src/pipeline-view/CreatePipelineDialog.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileManagerLocalContext.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useInitializePipelineEditor.tsx
Labels: improvement

#931 Feat/canvas context menu
  services/orchest-webserver/client/src/pipeline-view/CreateNextStepButton.tsx
  services/orchest-webserver/client/src/pipeline-view/PipelineEditor.tsx
  services/orchest-webserver/client/src/pipeline-view/PipelineStep.tsx
  services/orchest-webserver/client/src/pipeline-view/action-helpers/eventVarsHelpers.ts
  services/orchest-webserver/client/src/pipeline-view/hooks/useContextMenu.tsx
  services/orchest-webserver/client/src/pipeline-view/hooks/useEventVars.tsx
  services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineViewport.tsx
Labels: new feature request

#999 Prevent logged in user from deleting own account
  services/auth-server/app/app/views.py
  services/auth-server/client/src/views/Admin.tsx
Labels: improvement

#983 Add convenience installation script
  docs/source/fundamentals/jobs.rst
  docs/source/getting_started/installation.rst
  scripts/convenience_install.sh
Labels: new feature request

#1000 Disable opening file when the project has no pipeline
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileManagerContextMenu.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/FileTree.tsx
  services/orchest-webserver/client/src/pipeline-view/file-manager/TreeRow.tsx
Labels: fix

#1004 Fix issue: Command Palette is not callable in JupyterLab view
  services/orchest-webserver/client/src/App.tsx
  services/orchest-webserver/client/src/components/CommandPalette.tsx
  services/orchest-webserver/client/src/hooks/useHotKeys.ts
  services/orchest-webserver/client/src/jupyter/Jupyter.tsx
Labels: fix
